
Обнаружены ошибки в работе сайта. Проверить и исправить.
г. Москва, ул. Иркутская 11 к1 оф.135
Заказать звонок
admin
Выйти

Производство систем освещения
+7 (499) 113 27 70
+7 (499) 113 27 70
г. Москва, ул. Иркутская 11 к1 оф.135
Пн-Пт: 9:00-19:00 Cб-Вс: Выходной
info+161896@keosvet.ru
info+161896@keosvet.ru
Каталог товаров
Услуги
Наши проекты
Обзоры
Оплата и доставка
Гарантия
О Компании
Контакты

Главная
/ Каталог товаров
/ Торговое освещение
/ Встраиваемые линейные светильники
Встраиваемые линейные светильники
Подготовка проекта и расчет освещения
ФИЛЬТР
47
592
19
115
Торговое освещение
Дизайнерское освещение
Архитектурное освещение
Офисное освещение
Промышленное освещение
Уличное освещение
Взрывозащищенные
Освещение для ЖКХ
Комплектующие
Аварийное освещение
Сфера применения
Аналоги
Сортировка
NEW=;PRODUCT_DAY_DATE_START=;PRODUCT_DAY_DATE_END=;PRODUCT_DAY_DATE=;HIT=;RECOMMEND=;CATEGORY=;ORDER_USE=Да;BACKGROUND_IMAGE=;BACKGROUND_YOUTUBE=;NEWPRODUCT=;DISCOUNT=;TIME_BUY=;TIME_BUY_FROM=;TIME_BUY_TO=;DELIVERY=;GIFT=;GUARANTEE=2 года;ACCESSORIES=;MINIMUM_PRICE=;MOSHNOSTY_VT=36;NAPRAGENIE_V=185-265;CHASTOTA_GH=50;KOEFFICIENT_MOSHNOSTI=;SVETOVOY_POTOK_LM=3200, 3400;PYLSACHIA_SVETOVOGO_POTOKA=;CVETOVAY_TEMPERATYRA_K=;INDEKS_CVETOPEREDACHI_CRI=;TEMPERATURNY_DIAPAZON_T=0..+35°C;UGOL_RASSEIVANIA_GR=120;STEPENY_ZASHITY_IP=40;KLIMATICHESKOE_ISPOLNENIYE_UHL=4;KLASS_ELEKTROBEZOPASNOSTI=I;TIP_RASSEIVATELYA=;MATERIAL_KORPUSA=Сталь;TIP_YSTANOVKI=Универсальный;PROIZVODITELE_SVETODIODOV=;CHVET_KORPUSA=Белый;GABARITNYE_RAZMERY=1200x180x19;VZRYVOZASHITA=;KSS=Д;DISCOUNTS=;tip_pomesheniy=Внутренние помещения;vote_count=;vote_sum=;rating=;FORMA_KORPUSA=Прямоугольник;pylevlagozashchitnyy=ДА;TIP_KREPLENIY=;BAP=;kolichestvo_lamp=;tsokol=;datchiki=;ANALOG_DRL=;EMERGENCY=;EXPLOSION_PROOF=;DLINA=1200;WIDTH=180;HEIGHT=19;SHOW_IN_CATALOG=;MODEL_OFFICE=Армстронг;MODEL_LINERAL=;MODEL_EMERGENCY=;PURPOSE=;EMERGENCY_2=;FEATURES=;MOUNTING_HEIGHT=Высота до 4,5 метров;ACCESSORIES_2=;MODEL_INDUSTRIAL=;MODEL_UNPAVED=;MODEL_COMPONENTS=;MODEL_COMMERCIAL=;MODEL_DESIGN=;MODEL_STREET=;MODEL_EXPLOSION=;MODEL_architectural=;MODEL_ZHKH=;REQUEST_USE=;STORES_SHOW=;PICTURES=Array;ARTICLE=48509, 48510, 29682, 29681;BRAND=Feron;ADDITIONAL=;VIDEO=Array;DOCUMENTS=;ASSOCIATED=;RECOMMENDED=;SERVICES=;MAIN_BANNER_SHOW=;MAIN_BANNER_PICTURE=;MAIN_BANNER_THEME=;PROPERTY_TYPE=;PROPERTY_QUANTITY_OF_STRIPS=;PROPERTY_POWER=;PROPERTY_PROCREATOR=Россия;PROPERTY_SCOPE=;PROPERTY_DISPLAY=;PROPERTY_WEIGTH=;PROPERTY_ENERGY_CONSUMPTION=;PROPERTY_SETTINGS=;show =
Светильник AL2116 36W 4000K/6500K c ЭПРА
Мощность, 36 Вт
Cветовой 3200, 3400 Лм
Степень 40 IP
Габаритные 1200x180x19 мм
В наличии
1 551 ₽
NEW=;PRODUCT_DAY_DATE_START=;PRODUCT_DAY_DATE_END=;PRODUCT_DAY_DATE=;HIT=;RECOMMEND=Да;CATEGORY=Лучшее;ORDER_USE=Да;BACKGROUND_IMAGE=;BACKGROUND_YOUTUBE=;NEWPRODUCT=да;DISCOUNT=да;TIME_BUY=;TIME_BUY_FROM=;TIME_BUY_TO=;DELIVERY=;GIFT=;GUARANTEE=;ACCESSORIES=;MINIMUM_PRICE=;MOSHNOSTY_VT=;NAPRAGENIE_V=;CHASTOTA_GH=50;KOEFFICIENT_MOSHNOSTI=0,94;SVETOVOY_POTOK_LM=;PYLSACHIA_SVETOVOGO_POTOKA=;CVETOVAY_TEMPERATYRA_K=4500;INDEKS_CVETOPEREDACHI_CRI=CRI 75;TEMPERATURNY_DIAPAZON_T=;UGOL_RASSEIVANIA_GR=;STEPENY_ZASHITY_IP=;KLIMATICHESKOE_ISPOLNENIYE_UHL=1;KLASS_ELEKTROBEZOPASNOSTI=;TIP_RASSEIVATELYA=Прозрачный;MATERIAL_KORPUSA=Материал корпуса [MATERIAL_KORPUSA] {IP_PROP130};TIP_YSTANOVKI=Подвесной;PROIZVODITELE_SVETODIODOV=;CHVET_KORPUSA=;GABARITNYE_RAZMERY=;VZRYVOZASHITA=;KSS=;DISCOUNTS=;tip_pomesheniy=;vote_count=;vote_sum=;rating=;FORMA_KORPUSA=;pylevlagozashchitnyy=;TIP_KREPLENIY=;BAP=;kolichestvo_lamp=;tsokol=;datchiki=;ANALOG_DRL=;EMERGENCY=;EXPLOSION_PROOF=;DLINA=;WIDTH=;HEIGHT=;SHOW_IN_CATALOG=;MODEL_OFFICE=;MODEL_LINERAL=;MODEL_EMERGENCY=;PURPOSE=;EMERGENCY_2=;FEATURES=;MOUNTING_HEIGHT=;ACCESSORIES_2=;MODEL_INDUSTRIAL=;MODEL_UNPAVED=;MODEL_COMPONENTS=;MODEL_COMMERCIAL=;MODEL_DESIGN=;MODEL_STREET=;MODEL_EXPLOSION=;MODEL_architectural=;MODEL_ZHKH=;REQUEST_USE=;STORES_SHOW=;PICTURES=;ARTICLE=;BRAND=;ADDITIONAL=;VIDEO=;DOCUMENTS=Array;ASSOCIATED=;RECOMMENDED=;SERVICES=;MAIN_BANNER_SHOW=;MAIN_BANNER_PICTURE=;MAIN_BANNER_THEME=;PROPERTY_TYPE=;PROPERTY_QUANTITY_OF_STRIPS=;PROPERTY_POWER=;PROPERTY_PROCREATOR=;PROPERTY_SCOPE=;PROPERTY_DISPLAY=;PROPERTY_WEIGTH=;PROPERTY_ENERGY_CONSUMPTION=;PROPERTY_SETTINGS=;show =
TORGOVOE2_TEST
Рекомендуем
TORGOVOE2_TEST
Мощность, Вт
Cветовой Лм
Степень IP
Габаритные мм
В наличии 1 000
1 000 ₽
NEW=;PRODUCT_DAY_DATE_START=;PRODUCT_DAY_DATE_END=;PRODUCT_DAY_DATE=;HIT=;RECOMMEND=;CATEGORY=;ORDER_USE=;BACKGROUND_IMAGE=;BACKGROUND_YOUTUBE=;NEWPRODUCT=;DISCOUNT=;TIME_BUY=;TIME_BUY_FROM=;TIME_BUY_TO=;DELIVERY=;GIFT=;GUARANTEE=3 года;ACCESSORIES=;MINIMUM_PRICE=12487.18;MOSHNOSTY_VT=25.4;NAPRAGENIE_V=230;CHASTOTA_GH=;KOEFFICIENT_MOSHNOSTI=;SVETOVOY_POTOK_LM=975;PYLSACHIA_SVETOVOGO_POTOKA=;CVETOVAY_TEMPERATYRA_K=;INDEKS_CVETOPEREDACHI_CRI=CRI 85;TEMPERATURNY_DIAPAZON_T=–20… +45°C;UGOL_RASSEIVANIA_GR=110°;STEPENY_ZASHITY_IP=20;KLIMATICHESKOE_ISPOLNENIYE_UHL=;KLASS_ELEKTROBEZOPASNOSTI=;TIP_RASSEIVATELYA=;MATERIAL_KORPUSA=;TIP_YSTANOVKI=Встраиваемый;PROIZVODITELE_SVETODIODOV=;CHVET_KORPUSA=;GABARITNYE_RAZMERY=1080x62x32;VZRYVOZASHITA=;KSS=;DISCOUNTS=;tip_pomesheniy=;vote_count=;vote_sum=;rating=;FORMA_KORPUSA=;pylevlagozashchitnyy=;TIP_KREPLENIY=;BAP=;kolichestvo_lamp=;tsokol=;datchiki=;ANALOG_DRL=;EMERGENCY=;EXPLOSION_PROOF=;DLINA=1080;WIDTH=62;HEIGHT=32;SHOW_IN_CATALOG=;MODEL_OFFICE=;MODEL_LINERAL=;MODEL_EMERGENCY=;PURPOSE=;EMERGENCY_2=;FEATURES=;MOUNTING_HEIGHT=;ACCESSORIES_2=;MODEL_INDUSTRIAL=;MODEL_UNPAVED=;MODEL_COMPONENTS=;MODEL_COMMERCIAL=;MODEL_DESIGN=;MODEL_STREET=;MODEL_EXPLOSION=;MODEL_architectural=;MODEL_ZHKH=;REQUEST_USE=;STORES_SHOW=;PICTURES=;ARTICLE=37933;BRAND=6723;ADDITIONAL=;VIDEO=Array;DOCUMENTS=Array;ASSOCIATED=;RECOMMENDED=;SERVICES=;MAIN_BANNER_SHOW=;MAIN_BANNER_PICTURE=;MAIN_BANNER_THEME=;PROPERTY_TYPE=;PROPERTY_QUANTITY_OF_STRIPS=;PROPERTY_POWER=;PROPERTY_PROCREATOR=Россия;PROPERTY_SCOPE=;PROPERTY_DISPLAY=;PROPERTY_WEIGTH=1.64;PROPERTY_ENERGY_CONSUMPTION=;PROPERTY_SETTINGS=;show =
Светильник SP-LINE-BUILT-6232-1080-27W
Светильник SP-LINE-BUILT-6232-1080-27W
Мощность, 25.4 Вт
Cветовой 975 Лм
Степень 20 IP
Габаритные 1080x62x32 мм
В наличии 1
12 487.18 ₽
NEW=;PRODUCT_DAY_DATE_START=;PRODUCT_DAY_DATE_END=;PRODUCT_DAY_DATE=;HIT=;RECOMMEND=;CATEGORY=;ORDER_USE=;BACKGROUND_IMAGE=;BACKGROUND_YOUTUBE=;NEWPRODUCT=;DISCOUNT=;TIME_BUY=;TIME_BUY_FROM=;TIME_BUY_TO=;DELIVERY=;GIFT=;GUARANTEE=3 года;ACCESSORIES=;MINIMUM_PRICE=9961.32;MOSHNOSTY_VT=17.8;NAPRAGENIE_V=230;CHASTOTA_GH=;KOEFFICIENT_MOSHNOSTI=;SVETOVOY_POTOK_LM=680;PYLSACHIA_SVETOVOGO_POTOKA=;CVETOVAY_TEMPERATYRA_K=;INDEKS_CVETOPEREDACHI_CRI=CRI 85;TEMPERATURNY_DIAPAZON_T=–20… +45°C;UGOL_RASSEIVANIA_GR=110°;STEPENY_ZASHITY_IP=20;KLIMATICHESKOE_ISPOLNENIYE_UHL=;KLASS_ELEKTROBEZOPASNOSTI=;TIP_RASSEIVATELYA=;MATERIAL_KORPUSA=;TIP_YSTANOVKI=Встраиваемый;PROIZVODITELE_SVETODIODOV=;CHVET_KORPUSA=;GABARITNYE_RAZMERY=780x62x32;VZRYVOZASHITA=;KSS=;DISCOUNTS=;tip_pomesheniy=;vote_count=;vote_sum=;rating=;FORMA_KORPUSA=;pylevlagozashchitnyy=;TIP_KREPLENIY=;BAP=;kolichestvo_lamp=;tsokol=;datchiki=;ANALOG_DRL=;EMERGENCY=;EXPLOSION_PROOF=;DLINA=780;WIDTH=62;HEIGHT=32;SHOW_IN_CATALOG=;MODEL_OFFICE=;MODEL_LINERAL=;MODEL_EMERGENCY=;PURPOSE=;EMERGENCY_2=;FEATURES=;MOUNTING_HEIGHT=;ACCESSORIES_2=;MODEL_INDUSTRIAL=;MODEL_UNPAVED=;MODEL_COMPONENTS=;MODEL_COMMERCIAL=;MODEL_DESIGN=;MODEL_STREET=;MODEL_EXPLOSION=;MODEL_architectural=;MODEL_ZHKH=;REQUEST_USE=;STORES_SHOW=;PICTURES=;ARTICLE=37932;BRAND=6723;ADDITIONAL=;VIDEO=Array;DOCUMENTS=Array;ASSOCIATED=;RECOMMENDED=;SERVICES=;MAIN_BANNER_SHOW=;MAIN_BANNER_PICTURE=;MAIN_BANNER_THEME=;PROPERTY_TYPE=;PROPERTY_QUANTITY_OF_STRIPS=;PROPERTY_POWER=;PROPERTY_PROCREATOR=Россия;PROPERTY_SCOPE=;PROPERTY_DISPLAY=;PROPERTY_WEIGTH=1.46;PROPERTY_ENERGY_CONSUMPTION=;PROPERTY_SETTINGS=;show =
Светильник SP-LINE-BUILT-6232-780-19W Day4000 (ANOD, 230V)
Светильник SP-LINE-BUILT-6232-780-19W Day4000 (ANOD, 230V)
Мощность, 17.8 Вт
Cветовой 680 Лм
Степень 20 IP
Габаритные 780x62x32 мм
В наличии 1
9 961.32 ₽
NEW=;PRODUCT_DAY_DATE_START=;PRODUCT_DAY_DATE_END=;PRODUCT_DAY_DATE=;HIT=;RECOMMEND=;CATEGORY=;ORDER_USE=;BACKGROUND_IMAGE=;BACKGROUND_YOUTUBE=;NEWPRODUCT=;DISCOUNT=;TIME_BUY=;TIME_BUY_FROM=;TIME_BUY_TO=;DELIVERY=1-3 дня;GIFT=;GUARANTEE=3 года;ACCESSORIES=;MINIMUM_PRICE=12350;MOSHNOSTY_VT=100;NAPRAGENIE_V=176-264;CHASTOTA_GH=50;KOEFFICIENT_MOSHNOSTI=0,98;SVETOVOY_POTOK_LM=14000;PYLSACHIA_SVETOVOGO_POTOKA=>1;CVETOVAY_TEMPERATYRA_K=4000;INDEKS_CVETOPEREDACHI_CRI=CRI 80+;TEMPERATURNY_DIAPAZON_T=-0...+45 С;UGOL_RASSEIVANIA_GR=120;STEPENY_ZASHITY_IP=40;KLIMATICHESKOE_ISPOLNENIYE_UHL=4;KLASS_ELEKTROBEZOPASNOSTI=I;TIP_RASSEIVATELYA=Матовый;MATERIAL_KORPUSA=Алюминий;TIP_YSTANOVKI=Встраиваемый;PROIZVODITELE_SVETODIODOV=SAMSUNG;CHVET_KORPUSA=Серый;GABARITNYE_RAZMERY=2000x88x32;VZRYVOZASHITA=;KSS=Д;DISCOUNTS=;tip_pomesheniy=Торговые помещения и магазины;vote_count=;vote_sum=;rating=;FORMA_KORPUSA=;pylevlagozashchitnyy=НЕТ;TIP_KREPLENIY=;BAP=;kolichestvo_lamp=;tsokol=;datchiki=;ANALOG_DRL=;EMERGENCY=;EXPLOSION_PROOF=;DLINA=2000;WIDTH=88;HEIGHT=32;SHOW_IN_CATALOG=Да;MODEL_OFFICE=;MODEL_LINERAL=;MODEL_EMERGENCY=;PURPOSE=;EMERGENCY_2=;FEATURES=;MOUNTING_HEIGHT=;ACCESSORIES_2=;MODEL_INDUSTRIAL=;MODEL_UNPAVED=;MODEL_COMPONENTS=;MODEL_COMMERCIAL=;MODEL_DESIGN=;MODEL_STREET=;MODEL_EXPLOSION=;MODEL_architectural=;MODEL_ZHKH=;REQUEST_USE=;STORES_SHOW=;PICTURES=Array;ARTICLE=1008832;BRAND=5087;ADDITIONAL=;VIDEO=Array;DOCUMENTS=Array;ASSOCIATED=;RECOMMENDED=;SERVICES=;MAIN_BANNER_SHOW=;MAIN_BANNER_PICTURE=;MAIN_BANNER_THEME=;PROPERTY_TYPE=;PROPERTY_QUANTITY_OF_STRIPS=;PROPERTY_POWER=;PROPERTY_PROCREATOR=Россия;PROPERTY_SCOPE=;PROPERTY_DISPLAY=;PROPERTY_WEIGTH=6;PROPERTY_ENERGY_CONSUMPTION=;PROPERTY_SETTINGS=;show =
KEO Line-V 100W 2000х88х32мм
Мощность, 100 Вт
Cветовой 14000 Лм
Степень 40 IP
Габаритные 2000x88x32 мм
В наличии 1
12 350 ₽
NEW=;PRODUCT_DAY_DATE_START=;PRODUCT_DAY_DATE_END=;PRODUCT_DAY_DATE=;HIT=;RECOMMEND=;CATEGORY=;ORDER_USE=;BACKGROUND_IMAGE=;BACKGROUND_YOUTUBE=;NEWPRODUCT=;DISCOUNT=;TIME_BUY=;TIME_BUY_FROM=;TIME_BUY_TO=;DELIVERY=1-3 дня;GIFT=;GUARANTEE=3 года;ACCESSORIES=;MINIMUM_PRICE=8980;MOSHNOSTY_VT=80;NAPRAGENIE_V=176-264;CHASTOTA_GH=50;KOEFFICIENT_MOSHNOSTI=0,98;SVETOVOY_POTOK_LM=11200;PYLSACHIA_SVETOVOGO_POTOKA=>1;CVETOVAY_TEMPERATYRA_K=4000;INDEKS_CVETOPEREDACHI_CRI=CRI 80+;TEMPERATURNY_DIAPAZON_T=-0...+45 С;UGOL_RASSEIVANIA_GR=120;STEPENY_ZASHITY_IP=40;KLIMATICHESKOE_ISPOLNENIYE_UHL=4;KLASS_ELEKTROBEZOPASNOSTI=I;TIP_RASSEIVATELYA=Матовый;MATERIAL_KORPUSA=Алюминий;TIP_YSTANOVKI=Встраиваемый;PROIZVODITELE_SVETODIODOV=SAMSUNG;CHVET_KORPUSA=Серый;GABARITNYE_RAZMERY=1500x88x32;VZRYVOZASHITA=;KSS=Д;DISCOUNTS=;tip_pomesheniy=Торговые помещения и магазины;vote_count=;vote_sum=;rating=;FORMA_KORPUSA=;pylevlagozashchitnyy=НЕТ;TIP_KREPLENIY=;BAP=;kolichestvo_lamp=;tsokol=;datchiki=;ANALOG_DRL=;EMERGENCY=;EXPLOSION_PROOF=;DLINA=1500;WIDTH=88;HEIGHT=32;SHOW_IN_CATALOG=Да;MODEL_OFFICE=;MODEL_LINERAL=;MODEL_EMERGENCY=;PURPOSE=;EMERGENCY_2=;FEATURES=;MOUNTING_HEIGHT=;ACCESSORIES_2=;MODEL_INDUSTRIAL=;MODEL_UNPAVED=;MODEL_COMPONENTS=;MODEL_COMMERCIAL=;MODEL_DESIGN=;MODEL_STREET=;MODEL_EXPLOSION=;MODEL_architectural=;MODEL_ZHKH=;REQUEST_USE=;STORES_SHOW=;PICTURES=Array;ARTICLE=808832;BRAND=5087;ADDITIONAL=;VIDEO=Array;DOCUMENTS=Array;ASSOCIATED=;RECOMMENDED=;SERVICES=;MAIN_BANNER_SHOW=;MAIN_BANNER_PICTURE=;MAIN_BANNER_THEME=;PROPERTY_TYPE=;PROPERTY_QUANTITY_OF_STRIPS=;PROPERTY_POWER=;PROPERTY_PROCREATOR=Россия;PROPERTY_SCOPE=;PROPERTY_DISPLAY=;PROPERTY_WEIGTH=4;PROPERTY_ENERGY_CONSUMPTION=;PROPERTY_SETTINGS=;show =
KEO Line-V 80W 1500х88х32мм
Мощность, 80 Вт
Cветовой 11200 Лм
Степень 40 IP
Габаритные 1500x88x32 мм
В наличии 1
8 980 ₽
NEW=;PRODUCT_DAY_DATE_START=;PRODUCT_DAY_DATE_END=;PRODUCT_DAY_DATE=;HIT=;RECOMMEND=;CATEGORY=;ORDER_USE=;BACKGROUND_IMAGE=;BACKGROUND_YOUTUBE=;NEWPRODUCT=;DISCOUNT=;TIME_BUY=;TIME_BUY_FROM=;TIME_BUY_TO=;DELIVERY=1-3 дня;GIFT=;GUARANTEE=3 года;ACCESSORIES=;MINIMUM_PRICE=7650;MOSHNOSTY_VT=70;NAPRAGENIE_V=176-264;CHASTOTA_GH=50;KOEFFICIENT_MOSHNOSTI=0,98;SVETOVOY_POTOK_LM=9800;PYLSACHIA_SVETOVOGO_POTOKA=>1;CVETOVAY_TEMPERATYRA_K=4000;INDEKS_CVETOPEREDACHI_CRI=CRI 80+;TEMPERATURNY_DIAPAZON_T=-0...+45 С;UGOL_RASSEIVANIA_GR=120;STEPENY_ZASHITY_IP=40;KLIMATICHESKOE_ISPOLNENIYE_UHL=4;KLASS_ELEKTROBEZOPASNOSTI=I;TIP_RASSEIVATELYA=Матовый;MATERIAL_KORPUSA=Алюминий;TIP_YSTANOVKI=Встраиваемый;PROIZVODITELE_SVETODIODOV=SAMSUNG;CHVET_KORPUSA=Серый;GABARITNYE_RAZMERY=1200x88x32;VZRYVOZASHITA=;KSS=Д;DISCOUNTS=;tip_pomesheniy=Торговые помещения и магазины;vote_count=;vote_sum=;rating=;FORMA_KORPUSA=;pylevlagozashchitnyy=НЕТ;TIP_KREPLENIY=;BAP=;kolichestvo_lamp=;tsokol=;datchiki=;ANALOG_DRL=;EMERGENCY=;EXPLOSION_PROOF=;DLINA=1200;WIDTH=88;HEIGHT=32;SHOW_IN_CATALOG=Да;MODEL_OFFICE=;MODEL_LINERAL=;MODEL_EMERGENCY=;PURPOSE=;EMERGENCY_2=;FEATURES=;MOUNTING_HEIGHT=;ACCESSORIES_2=;MODEL_INDUSTRIAL=;MODEL_UNPAVED=;MODEL_COMPONENTS=;MODEL_COMMERCIAL=;MODEL_DESIGN=;MODEL_STREET=;MODEL_EXPLOSION=;MODEL_architectural=;MODEL_ZHKH=;REQUEST_USE=;STORES_SHOW=;PICTURES=Array;ARTICLE=708832;BRAND=5087;ADDITIONAL=;VIDEO=Array;DOCUMENTS=Array;ASSOCIATED=;RECOMMENDED=;SERVICES=;MAIN_BANNER_SHOW=;MAIN_BANNER_PICTURE=;MAIN_BANNER_THEME=;PROPERTY_TYPE=;PROPERTY_QUANTITY_OF_STRIPS=;PROPERTY_POWER=;PROPERTY_PROCREATOR=Россия;PROPERTY_SCOPE=;PROPERTY_DISPLAY=;PROPERTY_WEIGTH=3.5;PROPERTY_ENERGY_CONSUMPTION=;PROPERTY_SETTINGS=;show =
KEO Line-V 70W 1200х88х32мм
Мощность, 70 Вт
Cветовой 9800 Лм
Степень 40 IP
Габаритные 1200x88x32 мм
В наличии 1
7 650 ₽
NEW=;PRODUCT_DAY_DATE_START=;PRODUCT_DAY_DATE_END=;PRODUCT_DAY_DATE=;HIT=;RECOMMEND=;CATEGORY=;ORDER_USE=;BACKGROUND_IMAGE=;BACKGROUND_YOUTUBE=;NEWPRODUCT=;DISCOUNT=;TIME_BUY=;TIME_BUY_FROM=;TIME_BUY_TO=;DELIVERY=1-3 дня;GIFT=;GUARANTEE=3 года;ACCESSORIES=;MINIMUM_PRICE=6800;MOSHNOSTY_VT=50;NAPRAGENIE_V=176-264;CHASTOTA_GH=50;KOEFFICIENT_MOSHNOSTI=0,98;SVETOVOY_POTOK_LM=7000;PYLSACHIA_SVETOVOGO_POTOKA=>1;CVETOVAY_TEMPERATYRA_K=4000;INDEKS_CVETOPEREDACHI_CRI=CRI 80+;TEMPERATURNY_DIAPAZON_T=-0...+45 С;UGOL_RASSEIVANIA_GR=120;STEPENY_ZASHITY_IP=40;KLIMATICHESKOE_ISPOLNENIYE_UHL=4;KLASS_ELEKTROBEZOPASNOSTI=I;TIP_RASSEIVATELYA=Матовый;MATERIAL_KORPUSA=Алюминий;TIP_YSTANOVKI=Встраиваемый;PROIZVODITELE_SVETODIODOV=SAMSUNG;CHVET_KORPUSA=Серый;GABARITNYE_RAZMERY=1000x88x32;VZRYVOZASHITA=;KSS=Д;DISCOUNTS=;tip_pomesheniy=Торговые помещения и магазины;vote_count=;vote_sum=;rating=;FORMA_KORPUSA=;pylevlagozashchitnyy=НЕТ;TIP_KREPLENIY=;BAP=;kolichestvo_lamp=;tsokol=;datchiki=;ANALOG_DRL=;EMERGENCY=;EXPLOSION_PROOF=;DLINA=1000;WIDTH=88;HEIGHT=32;SHOW_IN_CATALOG=Да;MODEL_OFFICE=;MODEL_LINERAL=;MODEL_EMERGENCY=;PURPOSE=;EMERGENCY_2=;FEATURES=;MOUNTING_HEIGHT=;ACCESSORIES_2=;MODEL_INDUSTRIAL=;MODEL_UNPAVED=;MODEL_COMPONENTS=;MODEL_COMMERCIAL=;MODEL_DESIGN=;MODEL_STREET=;MODEL_EXPLOSION=;MODEL_architectural=;MODEL_ZHKH=;REQUEST_USE=;STORES_SHOW=;PICTURES=Array;ARTICLE=508832;BRAND=5087;ADDITIONAL=;VIDEO=Array;DOCUMENTS=Array;ASSOCIATED=;RECOMMENDED=;SERVICES=;MAIN_BANNER_SHOW=;MAIN_BANNER_PICTURE=;MAIN_BANNER_THEME=;PROPERTY_TYPE=;PROPERTY_QUANTITY_OF_STRIPS=;PROPERTY_POWER=;PROPERTY_PROCREATOR=Россия;PROPERTY_SCOPE=;PROPERTY_DISPLAY=;PROPERTY_WEIGTH=3;PROPERTY_ENERGY_CONSUMPTION=;PROPERTY_SETTINGS=;show =
KEO Line-V 50W 1000х88х32мм
Мощность, 50 Вт
Cветовой 7000 Лм
Степень 40 IP
Габаритные 1000x88x32 мм
В наличии 1
6 800 ₽
NEW=;PRODUCT_DAY_DATE_START=;PRODUCT_DAY_DATE_END=;PRODUCT_DAY_DATE=;HIT=;RECOMMEND=;CATEGORY=;ORDER_USE=;BACKGROUND_IMAGE=;BACKGROUND_YOUTUBE=;NEWPRODUCT=;DISCOUNT=;TIME_BUY=;TIME_BUY_FROM=;TIME_BUY_TO=;DELIVERY=1-3 дня;GIFT=;GUARANTEE=3 года;ACCESSORIES=;MINIMUM_PRICE=4500;MOSHNOSTY_VT=28;NAPRAGENIE_V=176-264;CHASTOTA_GH=50;KOEFFICIENT_MOSHNOSTI=0,98;SVETOVOY_POTOK_LM=3920;PYLSACHIA_SVETOVOGO_POTOKA=>1;CVETOVAY_TEMPERATYRA_K=4000;INDEKS_CVETOPEREDACHI_CRI=CRI 80+;TEMPERATURNY_DIAPAZON_T=-0...+45 С;UGOL_RASSEIVANIA_GR=120;STEPENY_ZASHITY_IP=40;KLIMATICHESKOE_ISPOLNENIYE_UHL=4;KLASS_ELEKTROBEZOPASNOSTI=I;TIP_RASSEIVATELYA=Матовый;MATERIAL_KORPUSA=Алюминий;TIP_YSTANOVKI=Встраиваемый;PROIZVODITELE_SVETODIODOV=;CHVET_KORPUSA=Серый;GABARITNYE_RAZMERY=500x88x32;VZRYVOZASHITA=;KSS=Д;DISCOUNTS=;tip_pomesheniy=Торговые помещения и магазины;vote_count=;vote_sum=;rating=;FORMA_KORPUSA=;pylevlagozashchitnyy=НЕТ;TIP_KREPLENIY=;BAP=;kolichestvo_lamp=;tsokol=;datchiki=;ANALOG_DRL=;EMERGENCY=;EXPLOSION_PROOF=;DLINA=500;WIDTH=88;HEIGHT=32;SHOW_IN_CATALOG=Да;MODEL_OFFICE=;MODEL_LINERAL=;MODEL_EMERGENCY=;PURPOSE=;EMERGENCY_2=;FEATURES=;MOUNTING_HEIGHT=;ACCESSORIES_2=;MODEL_INDUSTRIAL=;MODEL_UNPAVED=;MODEL_COMPONENTS=;MODEL_COMMERCIAL=;MODEL_DESIGN=;MODEL_STREET=;MODEL_EXPLOSION=;MODEL_architectural=;MODEL_ZHKH=;REQUEST_USE=;STORES_SHOW=;PICTURES=Array;ARTICLE=308832;BRAND=5087;ADDITIONAL=;VIDEO=Array;DOCUMENTS=Array;ASSOCIATED=;RECOMMENDED=;SERVICES=;MAIN_BANNER_SHOW=;MAIN_BANNER_PICTURE=;MAIN_BANNER_THEME=;PROPERTY_TYPE=;PROPERTY_QUANTITY_OF_STRIPS=;PROPERTY_POWER=;PROPERTY_PROCREATOR=Россия;PROPERTY_SCOPE=;PROPERTY_DISPLAY=;PROPERTY_WEIGTH=1,5;PROPERTY_ENERGY_CONSUMPTION=;PROPERTY_SETTINGS=;show =
KEO Line-V 30W 500х88х32мм
Мощность, 28 Вт
Cветовой 3920 Лм
Степень 40 IP
Габаритные 500x88x32 мм
В наличии 1
4 500 ₽
NEW=;PRODUCT_DAY_DATE_START=;PRODUCT_DAY_DATE_END=;PRODUCT_DAY_DATE=;HIT=;RECOMMEND=;CATEGORY=;ORDER_USE=;BACKGROUND_IMAGE=;BACKGROUND_YOUTUBE=;NEWPRODUCT=;DISCOUNT=;TIME_BUY=;TIME_BUY_FROM=;TIME_BUY_TO=;DELIVERY=1-3 дня;GIFT=;GUARANTEE=3 года;ACCESSORIES=;MINIMUM_PRICE=8450;MOSHNOSTY_VT=52;NAPRAGENIE_V=176-264;CHASTOTA_GH=50;KOEFFICIENT_MOSHNOSTI=0,98;SVETOVOY_POTOK_LM=7280;PYLSACHIA_SVETOVOGO_POTOKA=>1;CVETOVAY_TEMPERATYRA_K=4000;INDEKS_CVETOPEREDACHI_CRI=CRI 80+;TEMPERATURNY_DIAPAZON_T=-0...+45 С;UGOL_RASSEIVANIA_GR=120;STEPENY_ZASHITY_IP=40;KLIMATICHESKOE_ISPOLNENIYE_UHL=4;KLASS_ELEKTROBEZOPASNOSTI=I;TIP_RASSEIVATELYA=Матовый;MATERIAL_KORPUSA=Алюминий;TIP_YSTANOVKI=Встраиваемый;PROIZVODITELE_SVETODIODOV=SAMSUNG;CHVET_KORPUSA=Серый;GABARITNYE_RAZMERY=2000x63x32;VZRYVOZASHITA=;KSS=Д;DISCOUNTS=;tip_pomesheniy=Торговые помещения и магазины;vote_count=;vote_sum=;rating=;FORMA_KORPUSA=;pylevlagozashchitnyy=НЕТ;TIP_KREPLENIY=;BAP=;kolichestvo_lamp=;tsokol=;datchiki=;ANALOG_DRL=;EMERGENCY=;EXPLOSION_PROOF=;DLINA=2000;WIDTH=63;HEIGHT=32;SHOW_IN_CATALOG=Да;MODEL_OFFICE=;MODEL_LINERAL=;MODEL_EMERGENCY=;PURPOSE=;EMERGENCY_2=;FEATURES=;MOUNTING_HEIGHT=;ACCESSORIES_2=;MODEL_INDUSTRIAL=;MODEL_UNPAVED=;MODEL_COMPONENTS=;MODEL_COMMERCIAL=;MODEL_DESIGN=;MODEL_STREET=;MODEL_EXPLOSION=;MODEL_architectural=;MODEL_ZHKH=;REQUEST_USE=;STORES_SHOW=;PICTURES=Array;ARTICLE=506332;BRAND=5087;ADDITIONAL=;VIDEO=Array;DOCUMENTS=Array;ASSOCIATED=;RECOMMENDED=;SERVICES=;MAIN_BANNER_SHOW=;MAIN_BANNER_PICTURE=;MAIN_BANNER_THEME=;PROPERTY_TYPE=;PROPERTY_QUANTITY_OF_STRIPS=;PROPERTY_POWER=;PROPERTY_PROCREATOR=Россия;PROPERTY_SCOPE=;PROPERTY_DISPLAY=;PROPERTY_WEIGTH=4,2;PROPERTY_ENERGY_CONSUMPTION=;PROPERTY_SETTINGS=;show =
KEO Line-V 50W 2000х63х32мм
Мощность, 52 Вт
Cветовой 7280 Лм
Степень 40 IP
Габаритные 2000x63x32 мм
В наличии 1
8 450 ₽
NEW=;PRODUCT_DAY_DATE_START=;PRODUCT_DAY_DATE_END=;PRODUCT_DAY_DATE=;HIT=;RECOMMEND=;CATEGORY=;ORDER_USE=;BACKGROUND_IMAGE=;BACKGROUND_YOUTUBE=;NEWPRODUCT=;DISCOUNT=;TIME_BUY=;TIME_BUY_FROM=;TIME_BUY_TO=;DELIVERY=1-3 дня;GIFT=;GUARANTEE=3 года;ACCESSORIES=;MINIMUM_PRICE=6750;MOSHNOSTY_VT=40;NAPRAGENIE_V=176-264;CHASTOTA_GH=50;KOEFFICIENT_MOSHNOSTI=0,98;SVETOVOY_POTOK_LM=5600;PYLSACHIA_SVETOVOGO_POTOKA=>1;CVETOVAY_TEMPERATYRA_K=4000;INDEKS_CVETOPEREDACHI_CRI=CRI 80+;TEMPERATURNY_DIAPAZON_T=-0...+45 С;UGOL_RASSEIVANIA_GR=120;STEPENY_ZASHITY_IP=40;KLIMATICHESKOE_ISPOLNENIYE_UHL=4;KLASS_ELEKTROBEZOPASNOSTI=I;TIP_RASSEIVATELYA=Матовый;MATERIAL_KORPUSA=Алюминий;TIP_YSTANOVKI=Встраиваемый;PROIZVODITELE_SVETODIODOV=SAMSUNG;CHVET_KORPUSA=Серый;GABARITNYE_RAZMERY=1500x63x32;VZRYVOZASHITA=;KSS=Д;DISCOUNTS=;tip_pomesheniy=Торговые помещения и магазины;vote_count=;vote_sum=;rating=;FORMA_KORPUSA=;pylevlagozashchitnyy=НЕТ;TIP_KREPLENIY=;BAP=;kolichestvo_lamp=;tsokol=;datchiki=;ANALOG_DRL=;EMERGENCY=;EXPLOSION_PROOF=;DLINA=1500;WIDTH=63;HEIGHT=32;SHOW_IN_CATALOG=Да;MODEL_OFFICE=;MODEL_LINERAL=;MODEL_EMERGENCY=;PURPOSE=;EMERGENCY_2=;FEATURES=;MOUNTING_HEIGHT=;ACCESSORIES_2=;MODEL_INDUSTRIAL=;MODEL_UNPAVED=;MODEL_COMPONENTS=;MODEL_COMMERCIAL=;MODEL_DESIGN=;MODEL_STREET=;MODEL_EXPLOSION=;MODEL_architectural=;MODEL_ZHKH=;REQUEST_USE=;STORES_SHOW=;PICTURES=Array;ARTICLE=406332;BRAND=5087;ADDITIONAL=;VIDEO=Array;DOCUMENTS=Array;ASSOCIATED=;RECOMMENDED=;SERVICES=;MAIN_BANNER_SHOW=;MAIN_BANNER_PICTURE=;MAIN_BANNER_THEME=;PROPERTY_TYPE=;PROPERTY_QUANTITY_OF_STRIPS=;PROPERTY_POWER=;PROPERTY_PROCREATOR=Россия;PROPERTY_SCOPE=;PROPERTY_DISPLAY=;PROPERTY_WEIGTH=3,9;PROPERTY_ENERGY_CONSUMPTION=;PROPERTY_SETTINGS=;show =
KEO Line-V 40W 1500х63х32мм
Мощность, 40 Вт
Cветовой 5600 Лм
Степень 40 IP
Габаритные 1500x63x32 мм
В наличии 1
6 750 ₽
NEW=;PRODUCT_DAY_DATE_START=;PRODUCT_DAY_DATE_END=;PRODUCT_DAY_DATE=;HIT=;RECOMMEND=;CATEGORY=;ORDER_USE=;BACKGROUND_IMAGE=;BACKGROUND_YOUTUBE=;NEWPRODUCT=;DISCOUNT=;TIME_BUY=;TIME_BUY_FROM=;TIME_BUY_TO=;DELIVERY=1-3 дня;GIFT=;GUARANTEE=3 года;ACCESSORIES=;MINIMUM_PRICE=5800;MOSHNOSTY_VT=35;NAPRAGENIE_V=176-264;CHASTOTA_GH=50;KOEFFICIENT_MOSHNOSTI=0,98;SVETOVOY_POTOK_LM=4900;PYLSACHIA_SVETOVOGO_POTOKA=>1;CVETOVAY_TEMPERATYRA_K=4000;INDEKS_CVETOPEREDACHI_CRI=CRI 80+;TEMPERATURNY_DIAPAZON_T=-0...+45 С;UGOL_RASSEIVANIA_GR=120;STEPENY_ZASHITY_IP=40;KLIMATICHESKOE_ISPOLNENIYE_UHL=4;KLASS_ELEKTROBEZOPASNOSTI=I;TIP_RASSEIVATELYA=Матовый;MATERIAL_KORPUSA=Алюминий;TIP_YSTANOVKI=Встраиваемый;PROIZVODITELE_SVETODIODOV=SAMSUNG;CHVET_KORPUSA=Серый;GABARITNYE_RAZMERY=1200x63x32;VZRYVOZASHITA=;KSS=Д;DISCOUNTS=;tip_pomesheniy=Торговые помещения и магазины;vote_count=;vote_sum=;rating=;FORMA_KORPUSA=;pylevlagozashchitnyy=НЕТ;TIP_KREPLENIY=;BAP=;kolichestvo_lamp=;tsokol=;datchiki=;ANALOG_DRL=;EMERGENCY=;EXPLOSION_PROOF=;DLINA=1200;WIDTH=63;HEIGHT=32;SHOW_IN_CATALOG=Да;MODEL_OFFICE=;MODEL_LINERAL=;MODEL_EMERGENCY=;PURPOSE=;EMERGENCY_2=;FEATURES=;MOUNTING_HEIGHT=;ACCESSORIES_2=;MODEL_INDUSTRIAL=;MODEL_UNPAVED=;MODEL_COMPONENTS=;MODEL_COMMERCIAL=;MODEL_DESIGN=;MODEL_STREET=;MODEL_EXPLOSION=;MODEL_architectural=;MODEL_ZHKH=;REQUEST_USE=;STORES_SHOW=;PICTURES=Array;ARTICLE=356332;BRAND=5087;ADDITIONAL=;VIDEO=Array;DOCUMENTS=Array;ASSOCIATED=;RECOMMENDED=;SERVICES=;MAIN_BANNER_SHOW=;MAIN_BANNER_PICTURE=;MAIN_BANNER_THEME=;PROPERTY_TYPE=;PROPERTY_QUANTITY_OF_STRIPS=;PROPERTY_POWER=;PROPERTY_PROCREATOR=Россия;PROPERTY_SCOPE=;PROPERTY_DISPLAY=;PROPERTY_WEIGTH=3,9;PROPERTY_ENERGY_CONSUMPTION=;PROPERTY_SETTINGS=;show =
KEO Line-V 35W 1200х63х32мм
Мощность, 35 Вт
Cветовой 4900 Лм
Степень 40 IP
Габаритные 1200x63x32 мм
В наличии 1
5 800 ₽
NEW=;PRODUCT_DAY_DATE_START=;PRODUCT_DAY_DATE_END=;PRODUCT_DAY_DATE=;HIT=;RECOMMEND=;CATEGORY=;ORDER_USE=;BACKGROUND_IMAGE=;BACKGROUND_YOUTUBE=;NEWPRODUCT=;DISCOUNT=;TIME_BUY=;TIME_BUY_FROM=;TIME_BUY_TO=;DELIVERY=;GIFT=;GUARANTEE=3 года;ACCESSORIES=;MINIMUM_PRICE=4980;MOSHNOSTY_VT=28;NAPRAGENIE_V=176-264;CHASTOTA_GH=50;KOEFFICIENT_MOSHNOSTI=0,98;SVETOVOY_POTOK_LM=3920;PYLSACHIA_SVETOVOGO_POTOKA=>1;CVETOVAY_TEMPERATYRA_K=4000;INDEKS_CVETOPEREDACHI_CRI=CRI 80+;TEMPERATURNY_DIAPAZON_T=-0...+45 С;UGOL_RASSEIVANIA_GR=120;STEPENY_ZASHITY_IP=40;KLIMATICHESKOE_ISPOLNENIYE_UHL=4;KLASS_ELEKTROBEZOPASNOSTI=I;TIP_RASSEIVATELYA=Матовый;MATERIAL_KORPUSA=Алюминий;TIP_YSTANOVKI=Встраиваемый;PROIZVODITELE_SVETODIODOV=SAMSUNG;CHVET_KORPUSA=Серый;GABARITNYE_RAZMERY=1000x63x32;VZRYVOZASHITA=;KSS=Д;DISCOUNTS=;tip_pomesheniy=Торговые помещения и магазины;vote_count=;vote_sum=;rating=;FORMA_KORPUSA=;pylevlagozashchitnyy=НЕТ;TIP_KREPLENIY=;BAP=;kolichestvo_lamp=;tsokol=;datchiki=;ANALOG_DRL=;EMERGENCY=;EXPLOSION_PROOF=;DLINA=1000;WIDTH=63;HEIGHT=32;SHOW_IN_CATALOG=Да;MODEL_OFFICE=;MODEL_LINERAL=;MODEL_EMERGENCY=;PURPOSE=;EMERGENCY_2=;FEATURES=;MOUNTING_HEIGHT=;ACCESSORIES_2=;MODEL_INDUSTRIAL=;MODEL_UNPAVED=;MODEL_COMPONENTS=;MODEL_COMMERCIAL=;MODEL_DESIGN=;MODEL_STREET=;MODEL_EXPLOSION=;MODEL_architectural=;MODEL_ZHKH=;REQUEST_USE=;STORES_SHOW=;PICTURES=Array;ARTICLE=306332;BRAND=5087;ADDITIONAL=;VIDEO=Array;DOCUMENTS=Array;ASSOCIATED=;RECOMMENDED=;SERVICES=;MAIN_BANNER_SHOW=;MAIN_BANNER_PICTURE=;MAIN_BANNER_THEME=;PROPERTY_TYPE=;PROPERTY_QUANTITY_OF_STRIPS=;PROPERTY_POWER=;PROPERTY_PROCREATOR=Россия;PROPERTY_SCOPE=;PROPERTY_DISPLAY=;PROPERTY_WEIGTH=2,6;PROPERTY_ENERGY_CONSUMPTION=;PROPERTY_SETTINGS=;show =
KEO Line-V 30W 1000х63х32мм
Мощность, 28 Вт
Cветовой 3920 Лм
Степень 40 IP
Габаритные 1000x63x32 мм
В наличии 1
4 980 ₽
NEW=;PRODUCT_DAY_DATE_START=;PRODUCT_DAY_DATE_END=;PRODUCT_DAY_DATE=;HIT=;RECOMMEND=;CATEGORY=;ORDER_USE=;BACKGROUND_IMAGE=;BACKGROUND_YOUTUBE=;NEWPRODUCT=;DISCOUNT=;TIME_BUY=;TIME_BUY_FROM=;TIME_BUY_TO=;DELIVERY=;GIFT=;GUARANTEE=3 года;ACCESSORIES=;MINIMUM_PRICE=3650;MOSHNOSTY_VT=15;NAPRAGENIE_V=176-264;CHASTOTA_GH=50;KOEFFICIENT_MOSHNOSTI=0,98;SVETOVOY_POTOK_LM=2100;PYLSACHIA_SVETOVOGO_POTOKA=>1;CVETOVAY_TEMPERATYRA_K=4000;INDEKS_CVETOPEREDACHI_CRI=CRI 80+;TEMPERATURNY_DIAPAZON_T=-0...+45 С;UGOL_RASSEIVANIA_GR=120;STEPENY_ZASHITY_IP=40;KLIMATICHESKOE_ISPOLNENIYE_UHL=4;KLASS_ELEKTROBEZOPASNOSTI=I;TIP_RASSEIVATELYA=Матовый;MATERIAL_KORPUSA=Алюминий;TIP_YSTANOVKI=Встраиваемый;PROIZVODITELE_SVETODIODOV=;CHVET_KORPUSA=Серый;GABARITNYE_RAZMERY=500x63x32;VZRYVOZASHITA=;KSS=Д;DISCOUNTS=;tip_pomesheniy=Торговые помещения и магазины;vote_count=;vote_sum=;rating=;FORMA_KORPUSA=;pylevlagozashchitnyy=НЕТ;TIP_KREPLENIY=;BAP=;kolichestvo_lamp=;tsokol=;datchiki=;ANALOG_DRL=;EMERGENCY=;EXPLOSION_PROOF=;DLINA=500;WIDTH=63;HEIGHT=32;SHOW_IN_CATALOG=Да;MODEL_OFFICE=;MODEL_LINERAL=;MODEL_EMERGENCY=;PURPOSE=;EMERGENCY_2=;FEATURES=;MOUNTING_HEIGHT=;ACCESSORIES_2=;MODEL_INDUSTRIAL=;MODEL_UNPAVED=;MODEL_COMPONENTS=;MODEL_COMMERCIAL=;MODEL_DESIGN=;MODEL_STREET=;MODEL_EXPLOSION=;MODEL_architectural=;MODEL_ZHKH=;REQUEST_USE=;STORES_SHOW=;PICTURES=Array;ARTICLE=156332;BRAND=5087;ADDITIONAL=;VIDEO=Array;DOCUMENTS=Array;ASSOCIATED=;RECOMMENDED=;SERVICES=;MAIN_BANNER_SHOW=;MAIN_BANNER_PICTURE=;MAIN_BANNER_THEME=;PROPERTY_TYPE=;PROPERTY_QUANTITY_OF_STRIPS=;PROPERTY_POWER=;PROPERTY_PROCREATOR=Россия;PROPERTY_SCOPE=;PROPERTY_DISPLAY=;PROPERTY_WEIGTH=1,3;PROPERTY_ENERGY_CONSUMPTION=;PROPERTY_SETTINGS=;show =
KEO Line-V 15W 500х63х32мм
Мощность, 15 Вт
Cветовой 2100 Лм
Степень 40 IP
Габаритные 500x63x32 мм
В наличии 1
3 650 ₽
NEW=;PRODUCT_DAY_DATE_START=;PRODUCT_DAY_DATE_END=;PRODUCT_DAY_DATE=;HIT=;RECOMMEND=;CATEGORY=;ORDER_USE=;BACKGROUND_IMAGE=;BACKGROUND_YOUTUBE=;NEWPRODUCT=;DISCOUNT=;TIME_BUY=;TIME_BUY_FROM=;TIME_BUY_TO=;DELIVERY=;GIFT=;GUARANTEE=3 года;ACCESSORIES=;MINIMUM_PRICE=7450;MOSHNOSTY_VT=52;NAPRAGENIE_V=176-264;CHASTOTA_GH=50;KOEFFICIENT_MOSHNOSTI=0,98;SVETOVOY_POTOK_LM=7280;PYLSACHIA_SVETOVOGO_POTOKA=>1;CVETOVAY_TEMPERATYRA_K=4000;INDEKS_CVETOPEREDACHI_CRI=CRI 80+;TEMPERATURNY_DIAPAZON_T=-0...+45 С;UGOL_RASSEIVANIA_GR=120;STEPENY_ZASHITY_IP=40;KLIMATICHESKOE_ISPOLNENIYE_UHL=4;KLASS_ELEKTROBEZOPASNOSTI=I;TIP_RASSEIVATELYA=Матовый;MATERIAL_KORPUSA=Алюминий;TIP_YSTANOVKI=Встраиваемый;PROIZVODITELE_SVETODIODOV=SAMSUNG;CHVET_KORPUSA=Серый;GABARITNYE_RAZMERY=2000x49x32;VZRYVOZASHITA=;KSS=Д;DISCOUNTS=;tip_pomesheniy=Торговые помещения и магазины;vote_count=;vote_sum=;rating=;FORMA_KORPUSA=;pylevlagozashchitnyy=НЕТ;TIP_KREPLENIY=;BAP=;kolichestvo_lamp=;tsokol=;datchiki=;ANALOG_DRL=;EMERGENCY=;EXPLOSION_PROOF=;DLINA=2000;WIDTH=49;HEIGHT=32;SHOW_IN_CATALOG=Да;MODEL_OFFICE=;MODEL_LINERAL=;MODEL_EMERGENCY=;PURPOSE=;EMERGENCY_2=;FEATURES=;MOUNTING_HEIGHT=;ACCESSORIES_2=;MODEL_INDUSTRIAL=;MODEL_UNPAVED=;MODEL_COMPONENTS=;MODEL_COMMERCIAL=;MODEL_DESIGN=;MODEL_STREET=;MODEL_EXPLOSION=;MODEL_architectural=;MODEL_ZHKH=;REQUEST_USE=;STORES_SHOW=;PICTURES=Array;ARTICLE=354932;BRAND=5087;ADDITIONAL=;VIDEO=Array;DOCUMENTS=Array;ASSOCIATED=;RECOMMENDED=;SERVICES=;MAIN_BANNER_SHOW=;MAIN_BANNER_PICTURE=;MAIN_BANNER_THEME=;PROPERTY_TYPE=;PROPERTY_QUANTITY_OF_STRIPS=;PROPERTY_POWER=;PROPERTY_PROCREATOR=Россия;PROPERTY_SCOPE=;PROPERTY_DISPLAY=;PROPERTY_WEIGTH=4;PROPERTY_ENERGY_CONSUMPTION=;PROPERTY_SETTINGS=;show =
KEO Line-V 52W 2000х49х32мм
Мощность, 52 Вт
Cветовой 7280 Лм
Степень 40 IP
Габаритные 2000x49x32 мм
В наличии 1
7 450 ₽
NEW=;PRODUCT_DAY_DATE_START=;PRODUCT_DAY_DATE_END=;PRODUCT_DAY_DATE=;HIT=;RECOMMEND=;CATEGORY=;ORDER_USE=;BACKGROUND_IMAGE=;BACKGROUND_YOUTUBE=;NEWPRODUCT=;DISCOUNT=;TIME_BUY=;TIME_BUY_FROM=;TIME_BUY_TO=;DELIVERY=;GIFT=;GUARANTEE=3 года;ACCESSORIES=;MINIMUM_PRICE=6200;MOSHNOSTY_VT=40;NAPRAGENIE_V=176-264;CHASTOTA_GH=50;KOEFFICIENT_MOSHNOSTI=0,98;SVETOVOY_POTOK_LM=5600;PYLSACHIA_SVETOVOGO_POTOKA=>1;CVETOVAY_TEMPERATYRA_K=4000;INDEKS_CVETOPEREDACHI_CRI=CRI 80+;TEMPERATURNY_DIAPAZON_T=-0...+45 С;UGOL_RASSEIVANIA_GR=120;STEPENY_ZASHITY_IP=40;KLIMATICHESKOE_ISPOLNENIYE_UHL=4;KLASS_ELEKTROBEZOPASNOSTI=I;TIP_RASSEIVATELYA=Матовый;MATERIAL_KORPUSA=Алюминий;TIP_YSTANOVKI=Встраиваемый;PROIZVODITELE_SVETODIODOV=SAMSUNG;CHVET_KORPUSA=Серый;GABARITNYE_RAZMERY=1500x49x32;VZRYVOZASHITA=;KSS=Д;DISCOUNTS=;tip_pomesheniy=Торговые помещения и магазины;vote_count=;vote_sum=;rating=;FORMA_KORPUSA=;pylevlagozashchitnyy=НЕТ;TIP_KREPLENIY=;BAP=;kolichestvo_lamp=;tsokol=;datchiki=;ANALOG_DRL=;EMERGENCY=;EXPLOSION_PROOF=;DLINA=1500;WIDTH=49;HEIGHT=32;SHOW_IN_CATALOG=Да;MODEL_OFFICE=;MODEL_LINERAL=;MODEL_EMERGENCY=;PURPOSE=;EMERGENCY_2=;FEATURES=;MOUNTING_HEIGHT=;ACCESSORIES_2=;MODEL_INDUSTRIAL=;MODEL_UNPAVED=;MODEL_COMPONENTS=;MODEL_COMMERCIAL=;MODEL_DESIGN=;MODEL_STREET=;MODEL_EXPLOSION=;MODEL_architectural=;MODEL_ZHKH=;REQUEST_USE=;STORES_SHOW=;PICTURES=Array;ARTICLE=354932;BRAND=5087;ADDITIONAL=;VIDEO=Array;DOCUMENTS=Array;ASSOCIATED=;RECOMMENDED=;SERVICES=;MAIN_BANNER_SHOW=;MAIN_BANNER_PICTURE=;MAIN_BANNER_THEME=;PROPERTY_TYPE=;PROPERTY_QUANTITY_OF_STRIPS=;PROPERTY_POWER=;PROPERTY_PROCREATOR=Россия;PROPERTY_SCOPE=;PROPERTY_DISPLAY=;PROPERTY_WEIGTH=3;PROPERTY_ENERGY_CONSUMPTION=;PROPERTY_SETTINGS=;show =
KEO Line-V 40W 1500х49х32мм
Мощность, 40 Вт
Cветовой 5600 Лм
Степень 40 IP
Габаритные 1500x49x32 мм
В наличии 1
6 200 ₽
NEW=;PRODUCT_DAY_DATE_START=;PRODUCT_DAY_DATE_END=;PRODUCT_DAY_DATE=;HIT=;RECOMMEND=;CATEGORY=;ORDER_USE=;BACKGROUND_IMAGE=;BACKGROUND_YOUTUBE=;NEWPRODUCT=;DISCOUNT=;TIME_BUY=;TIME_BUY_FROM=;TIME_BUY_TO=;DELIVERY=;GIFT=;GUARANTEE=3 года;ACCESSORIES=;MINIMUM_PRICE=5300;MOSHNOSTY_VT=35;NAPRAGENIE_V=176-264;CHASTOTA_GH=50;KOEFFICIENT_MOSHNOSTI=0,98;SVETOVOY_POTOK_LM=4900;PYLSACHIA_SVETOVOGO_POTOKA=>1;CVETOVAY_TEMPERATYRA_K=4000;INDEKS_CVETOPEREDACHI_CRI=CRI 80+;TEMPERATURNY_DIAPAZON_T=-0...+45 С;UGOL_RASSEIVANIA_GR=120;STEPENY_ZASHITY_IP=40;KLIMATICHESKOE_ISPOLNENIYE_UHL=4;KLASS_ELEKTROBEZOPASNOSTI=I;TIP_RASSEIVATELYA=Матовый;MATERIAL_KORPUSA=Алюминий;TIP_YSTANOVKI=Встраиваемый;PROIZVODITELE_SVETODIODOV=SAMSUNG;CHVET_KORPUSA=Серый;GABARITNYE_RAZMERY=1200x49x32;VZRYVOZASHITA=;KSS=Д;DISCOUNTS=;tip_pomesheniy=Торговые помещения и магазины;vote_count=;vote_sum=;rating=;FORMA_KORPUSA=;pylevlagozashchitnyy=НЕТ;TIP_KREPLENIY=;BAP=;kolichestvo_lamp=;tsokol=;datchiki=;ANALOG_DRL=;EMERGENCY=;EXPLOSION_PROOF=;DLINA=1200;WIDTH=49;HEIGHT=32;SHOW_IN_CATALOG=Да;MODEL_OFFICE=;MODEL_LINERAL=;MODEL_EMERGENCY=;PURPOSE=;EMERGENCY_2=;FEATURES=;MOUNTING_HEIGHT=;ACCESSORIES_2=;MODEL_INDUSTRIAL=;MODEL_UNPAVED=;MODEL_COMPONENTS=;MODEL_COMMERCIAL=;MODEL_DESIGN=;MODEL_STREET=;MODEL_EXPLOSION=;MODEL_architectural=;MODEL_ZHKH=;REQUEST_USE=;STORES_SHOW=;PICTURES=Array;ARTICLE=354932;BRAND=5087;ADDITIONAL=;VIDEO=Array;DOCUMENTS=Array;ASSOCIATED=;RECOMMENDED=;SERVICES=;MAIN_BANNER_SHOW=;MAIN_BANNER_PICTURE=;MAIN_BANNER_THEME=;PROPERTY_TYPE=;PROPERTY_QUANTITY_OF_STRIPS=;PROPERTY_POWER=;PROPERTY_PROCREATOR=Россия;PROPERTY_SCOPE=;PROPERTY_DISPLAY=;PROPERTY_WEIGTH=2,3;PROPERTY_ENERGY_CONSUMPTION=;PROPERTY_SETTINGS=;show =
KEO Line-V 35W 1200х49х32мм
Мощность, 35 Вт
Cветовой 4900 Лм
Степень 40 IP
Габаритные 1200x49x32 мм
В наличии 1
5 300 ₽
NEW=;PRODUCT_DAY_DATE_START=;PRODUCT_DAY_DATE_END=;PRODUCT_DAY_DATE=;HIT=;RECOMMEND=;CATEGORY=;ORDER_USE=;BACKGROUND_IMAGE=;BACKGROUND_YOUTUBE=;NEWPRODUCT=;DISCOUNT=;TIME_BUY=;TIME_BUY_FROM=;TIME_BUY_TO=;DELIVERY=;GIFT=;GUARANTEE=3 года;ACCESSORIES=;MINIMUM_PRICE=4500;MOSHNOSTY_VT=28;NAPRAGENIE_V=176-264;CHASTOTA_GH=50;KOEFFICIENT_MOSHNOSTI=0,98;SVETOVOY_POTOK_LM=3920;PYLSACHIA_SVETOVOGO_POTOKA=>1;CVETOVAY_TEMPERATYRA_K=4000;INDEKS_CVETOPEREDACHI_CRI=CRI 80+;TEMPERATURNY_DIAPAZON_T=-0...+45 С;UGOL_RASSEIVANIA_GR=120;STEPENY_ZASHITY_IP=40;KLIMATICHESKOE_ISPOLNENIYE_UHL=4;KLASS_ELEKTROBEZOPASNOSTI=I;TIP_RASSEIVATELYA=Матовый;MATERIAL_KORPUSA=Алюминий;TIP_YSTANOVKI=Встраиваемый;PROIZVODITELE_SVETODIODOV=SAMSUNG;CHVET_KORPUSA=Серый;GABARITNYE_RAZMERY=1000x49x32;VZRYVOZASHITA=;KSS=Д;DISCOUNTS=;tip_pomesheniy=Торговые помещения и магазины;vote_count=;vote_sum=;rating=;FORMA_KORPUSA=;pylevlagozashchitnyy=НЕТ;TIP_KREPLENIY=;BAP=;kolichestvo_lamp=;tsokol=;datchiki=;ANALOG_DRL=;EMERGENCY=;EXPLOSION_PROOF=;DLINA=1000;WIDTH=49;HEIGHT=32;SHOW_IN_CATALOG=Да;MODEL_OFFICE=;MODEL_LINERAL=;MODEL_EMERGENCY=;PURPOSE=;EMERGENCY_2=;FEATURES=;MOUNTING_HEIGHT=;ACCESSORIES_2=;MODEL_INDUSTRIAL=;MODEL_UNPAVED=;MODEL_COMPONENTS=;MODEL_COMMERCIAL=;MODEL_DESIGN=;MODEL_STREET=;MODEL_EXPLOSION=;MODEL_architectural=;MODEL_ZHKH=;REQUEST_USE=;STORES_SHOW=;PICTURES=Array;ARTICLE=6001;BRAND=5087;ADDITIONAL=;VIDEO=Array;DOCUMENTS=Array;ASSOCIATED=;RECOMMENDED=;SERVICES=;MAIN_BANNER_SHOW=;MAIN_BANNER_PICTURE=;MAIN_BANNER_THEME=;PROPERTY_TYPE=;PROPERTY_QUANTITY_OF_STRIPS=;PROPERTY_POWER=;PROPERTY_PROCREATOR=Россия;PROPERTY_SCOPE=;PROPERTY_DISPLAY=;PROPERTY_WEIGTH=2;PROPERTY_ENERGY_CONSUMPTION=;PROPERTY_SETTINGS=;show =
KEO Line-V 30W 1000х49х32мм
Мощность, 28 Вт
Cветовой 3920 Лм
Степень 40 IP
Габаритные 1000x49x32 мм
В наличии 1
4 500 ₽
NEW=;PRODUCT_DAY_DATE_START=;PRODUCT_DAY_DATE_END=;PRODUCT_DAY_DATE=;HIT=;RECOMMEND=;CATEGORY=;ORDER_USE=;BACKGROUND_IMAGE=;BACKGROUND_YOUTUBE=;NEWPRODUCT=;DISCOUNT=;TIME_BUY=;TIME_BUY_FROM=;TIME_BUY_TO=;DELIVERY=;GIFT=;GUARANTEE=3 года;ACCESSORIES=;MINIMUM_PRICE=3480;MOSHNOSTY_VT=15;NAPRAGENIE_V=176-264;CHASTOTA_GH=50;KOEFFICIENT_MOSHNOSTI=0,98;SVETOVOY_POTOK_LM=2100;PYLSACHIA_SVETOVOGO_POTOKA=>1;CVETOVAY_TEMPERATYRA_K=4000;INDEKS_CVETOPEREDACHI_CRI=CRI 80+;TEMPERATURNY_DIAPAZON_T=-0...+45 С;UGOL_RASSEIVANIA_GR=120;STEPENY_ZASHITY_IP=40;KLIMATICHESKOE_ISPOLNENIYE_UHL=4;KLASS_ELEKTROBEZOPASNOSTI=I;TIP_RASSEIVATELYA=Матовый;MATERIAL_KORPUSA=Алюминий;TIP_YSTANOVKI=Встраиваемый;PROIZVODITELE_SVETODIODOV=;CHVET_KORPUSA=Черный;GABARITNYE_RAZMERY=500x49x32;VZRYVOZASHITA=;KSS=Д;DISCOUNTS=;tip_pomesheniy=Торговые помещения и магазины;vote_count=;vote_sum=;rating=;FORMA_KORPUSA=;pylevlagozashchitnyy=НЕТ;TIP_KREPLENIY=;BAP=;kolichestvo_lamp=;tsokol=;datchiki=;ANALOG_DRL=;EMERGENCY=;EXPLOSION_PROOF=;DLINA=500;WIDTH=49;HEIGHT=32;SHOW_IN_CATALOG=Да;MODEL_OFFICE=;MODEL_LINERAL=;MODEL_EMERGENCY=;PURPOSE=;EMERGENCY_2=;FEATURES=;MOUNTING_HEIGHT=;ACCESSORIES_2=;MODEL_INDUSTRIAL=;MODEL_UNPAVED=;MODEL_COMPONENTS=;MODEL_COMMERCIAL=;MODEL_DESIGN=;MODEL_STREET=;MODEL_EXPLOSION=;MODEL_architectural=;MODEL_ZHKH=;REQUEST_USE=;STORES_SHOW=;PICTURES=Array;ARTICLE=6001;BRAND=5087;ADDITIONAL=;VIDEO=Array;DOCUMENTS=Array;ASSOCIATED=;RECOMMENDED=;SERVICES=;MAIN_BANNER_SHOW=;MAIN_BANNER_PICTURE=;MAIN_BANNER_THEME=;PROPERTY_TYPE=;PROPERTY_QUANTITY_OF_STRIPS=;PROPERTY_POWER=;PROPERTY_PROCREATOR=Россия;PROPERTY_SCOPE=;PROPERTY_DISPLAY=;PROPERTY_WEIGTH=1;PROPERTY_ENERGY_CONSUMPTION=;PROPERTY_SETTINGS=;show =
KEO Line-V 15W 500х49х32мм
Мощность, 15 Вт
Cветовой 2100 Лм
Степень 40 IP
Габаритные 500x49x32 мм
В наличии 1
3 480 ₽
NEW=;PRODUCT_DAY_DATE_START=;PRODUCT_DAY_DATE_END=;PRODUCT_DAY_DATE=;HIT=;RECOMMEND=;CATEGORY=;ORDER_USE=;BACKGROUND_IMAGE=;BACKGROUND_YOUTUBE=;NEWPRODUCT=;DISCOUNT=;TIME_BUY=;TIME_BUY_FROM=;TIME_BUY_TO=;DELIVERY=;GIFT=;GUARANTEE=5 лет;ACCESSORIES=;MINIMUM_PRICE=0;MOSHNOSTY_VT=37;NAPRAGENIE_V=198-264;CHASTOTA_GH=50;KOEFFICIENT_MOSHNOSTI=0,98;SVETOVOY_POTOK_LM=3527;PYLSACHIA_SVETOVOGO_POTOKA=;CVETOVAY_TEMPERATYRA_K=4000;INDEKS_CVETOPEREDACHI_CRI=CRI 80+;TEMPERATURNY_DIAPAZON_T=0°...+40°С;UGOL_RASSEIVANIA_GR=120;STEPENY_ZASHITY_IP=65;KLIMATICHESKOE_ISPOLNENIYE_UHL=4;KLASS_ELEKTROBEZOPASNOSTI=I;TIP_RASSEIVATELYA=Матовый;MATERIAL_KORPUSA=Алюминий;TIP_YSTANOVKI=Встраиваемый;PROIZVODITELE_SVETODIODOV=;CHVET_KORPUSA=Серый;GABARITNYE_RAZMERY=1226х100х91;VZRYVOZASHITA=;KSS=Д;DISCOUNTS=;tip_pomesheniy=Торговые помещения и магазины;vote_count=;vote_sum=;rating=;FORMA_KORPUSA=;pylevlagozashchitnyy=;TIP_KREPLENIY=;BAP=;kolichestvo_lamp=;tsokol=;datchiki=;ANALOG_DRL=;EMERGENCY=;EXPLOSION_PROOF=;DLINA=1226;WIDTH=100;HEIGHT=91;SHOW_IN_CATALOG=;MODEL_OFFICE=;MODEL_LINERAL=;MODEL_EMERGENCY=;PURPOSE=;EMERGENCY_2=;FEATURES=;MOUNTING_HEIGHT=;ACCESSORIES_2=;MODEL_INDUSTRIAL=;MODEL_UNPAVED=;MODEL_COMPONENTS=;MODEL_COMMERCIAL=;MODEL_DESIGN=;MODEL_STREET=;MODEL_EXPLOSION=;MODEL_architectural=;MODEL_ZHKH=;REQUEST_USE=;STORES_SHOW=;PICTURES=Array;ARTICLE=ДВО45-40-001 Liner R 840;BRAND=110;ADDITIONAL=;VIDEO=Array;DOCUMENTS=Array;ASSOCIATED=;RECOMMENDED=;SERVICES=;MAIN_BANNER_SHOW=;MAIN_BANNER_PICTURE=;MAIN_BANNER_THEME=;PROPERTY_TYPE=;PROPERTY_QUANTITY_OF_STRIPS=;PROPERTY_POWER=;PROPERTY_PROCREATOR=Россия;PROPERTY_SCOPE=;PROPERTY_DISPLAY=;PROPERTY_WEIGTH=3.1;PROPERTY_ENERGY_CONSUMPTION=;PROPERTY_SETTINGS=;show =
АСТЗ ДВО45-40 Liner R 840
Мощность, 37 Вт
Cветовой 3527 Лм
Степень 65 IP
Габаритные 1226х100х91 мм
В наличии 1
0 ₽
NEW=;PRODUCT_DAY_DATE_START=;PRODUCT_DAY_DATE_END=;PRODUCT_DAY_DATE=;HIT=;RECOMMEND=;CATEGORY=;ORDER_USE=;BACKGROUND_IMAGE=;BACKGROUND_YOUTUBE=;NEWPRODUCT=;DISCOUNT=;TIME_BUY=;TIME_BUY_FROM=;TIME_BUY_TO=;DELIVERY=;GIFT=;GUARANTEE=3 года;ACCESSORIES=;MINIMUM_PRICE=4050;MOSHNOSTY_VT=33;NAPRAGENIE_V=175-260;CHASTOTA_GH=50;KOEFFICIENT_MOSHNOSTI=0,9;SVETOVOY_POTOK_LM=2600;PYLSACHIA_SVETOVOGO_POTOKA=;CVETOVAY_TEMPERATYRA_K=5000;INDEKS_CVETOPEREDACHI_CRI=CRI 80+;TEMPERATURNY_DIAPAZON_T=0°...+40°С;UGOL_RASSEIVANIA_GR=120;STEPENY_ZASHITY_IP=40;KLIMATICHESKOE_ISPOLNENIYE_UHL=4;KLASS_ELEKTROBEZOPASNOSTI=I;TIP_RASSEIVATELYA=Матовый;MATERIAL_KORPUSA=Алюминий;TIP_YSTANOVKI=Встраиваемый;PROIZVODITELE_SVETODIODOV=NICHIA;CHVET_KORPUSA=Серый;GABARITNYE_RAZMERY=1210х134х78;VZRYVOZASHITA=;KSS=Д;DISCOUNTS=;tip_pomesheniy=Офисные помещения;vote_count=;vote_sum=;rating=;FORMA_KORPUSA=;pylevlagozashchitnyy=;TIP_KREPLENIY=;BAP=;kolichestvo_lamp=;tsokol=;datchiki=;ANALOG_DRL=;EMERGENCY=;EXPLOSION_PROOF=;DLINA=1210;WIDTH=134;HEIGHT=78;SHOW_IN_CATALOG=;MODEL_OFFICE=;MODEL_LINERAL=;MODEL_EMERGENCY=;PURPOSE=;EMERGENCY_2=;FEATURES=;MOUNTING_HEIGHT=;ACCESSORIES_2=;MODEL_INDUSTRIAL=;MODEL_UNPAVED=;MODEL_COMPONENTS=;MODEL_COMMERCIAL=;MODEL_DESIGN=;MODEL_STREET=;MODEL_EXPLOSION=;MODEL_architectural=;MODEL_ZHKH=;REQUEST_USE=;STORES_SHOW=;PICTURES=Array;ARTICLE=LE-СВО-03-033-1417-40Х / LE-СВО-03-033-1418-40Д / LE-СВО-03-033-1419-40Т;BRAND=106;ADDITIONAL=;VIDEO=Array;DOCUMENTS=Array;ASSOCIATED=;RECOMMENDED=;SERVICES=;MAIN_BANNER_SHOW=;MAIN_BANNER_PICTURE=;MAIN_BANNER_THEME=;PROPERTY_TYPE=;PROPERTY_QUANTITY_OF_STRIPS=;PROPERTY_POWER=;PROPERTY_PROCREATOR=Россия;PROPERTY_SCOPE=;PROPERTY_DISPLAY=;PROPERTY_WEIGTH=1.9;PROPERTY_ENERGY_CONSUMPTION=;PROPERTY_SETTINGS=;show =
LEDeffect ОФИС РОКФОН 33/1200
Мощность, 33 Вт
Cветовой 2600 Лм
Степень 40 IP
Габаритные 1210х134х78 мм
В наличии 1
4 050 ₽
NEW=;PRODUCT_DAY_DATE_START=;PRODUCT_DAY_DATE_END=;PRODUCT_DAY_DATE=;HIT=;RECOMMEND=;CATEGORY=;ORDER_USE=;BACKGROUND_IMAGE=;BACKGROUND_YOUTUBE=;NEWPRODUCT=;DISCOUNT=;TIME_BUY=;TIME_BUY_FROM=;TIME_BUY_TO=;DELIVERY=;GIFT=;GUARANTEE=3 года;ACCESSORIES=;MINIMUM_PRICE=15430;MOSHNOSTY_VT=80;NAPRAGENIE_V=175-260;CHASTOTA_GH=50;KOEFFICIENT_MOSHNOSTI=0,98;SVETOVOY_POTOK_LM=7400;PYLSACHIA_SVETOVOGO_POTOKA=;CVETOVAY_TEMPERATYRA_K=4000;INDEKS_CVETOPEREDACHI_CRI=CRI 80+;TEMPERATURNY_DIAPAZON_T=0°...+45°С;UGOL_RASSEIVANIA_GR=120;STEPENY_ZASHITY_IP=20;KLIMATICHESKOE_ISPOLNENIYE_UHL=4;KLASS_ELEKTROBEZOPASNOSTI=I;TIP_RASSEIVATELYA=Матовый;MATERIAL_KORPUSA=;TIP_YSTANOVKI=Встраиваемый;PROIZVODITELE_SVETODIODOV=NICHIA;CHVET_KORPUSA=Белый;GABARITNYE_RAZMERY=1958х94х115;VZRYVOZASHITA=;KSS=Д;DISCOUNTS=;tip_pomesheniy=Чистые помещения;vote_count=;vote_sum=;rating=;FORMA_KORPUSA=;pylevlagozashchitnyy=НЕТ;TIP_KREPLENIY=;BAP=;kolichestvo_lamp=;tsokol=;datchiki=;ANALOG_DRL=;EMERGENCY=;EXPLOSION_PROOF=;DLINA=1958;WIDTH=94;HEIGHT=115;SHOW_IN_CATALOG=;MODEL_OFFICE=;MODEL_LINERAL=;MODEL_EMERGENCY=;PURPOSE=;EMERGENCY_2=;FEATURES=;MOUNTING_HEIGHT=;ACCESSORIES_2=;MODEL_INDUSTRIAL=;MODEL_UNPAVED=;MODEL_COMPONENTS=;MODEL_COMMERCIAL=;MODEL_DESIGN=;MODEL_STREET=;MODEL_EXPLOSION=;MODEL_architectural=;MODEL_ZHKH=;REQUEST_USE=;STORES_SHOW=;PICTURES=Array;ARTICLE=LE-СВО-23-080-1453-20Х / LE-СВО-23-080-1454-20Д / LE-СВО-23-080-1455-20Т;BRAND=106;ADDITIONAL=;VIDEO=Array;DOCUMENTS=Array;ASSOCIATED=;RECOMMENDED=;SERVICES=;MAIN_BANNER_SHOW=;MAIN_BANNER_PICTURE=;MAIN_BANNER_THEME=;PROPERTY_TYPE=;PROPERTY_QUANTITY_OF_STRIPS=;PROPERTY_POWER=;PROPERTY_PROCREATOR=Россия;PROPERTY_SCOPE=;PROPERTY_DISPLAY=;PROPERTY_WEIGTH=6.3;PROPERTY_ENERGY_CONSUMPTION=;PROPERTY_SETTINGS=;show =
LEDeffect СТРЕЛА СВО 80
Мощность, 80 Вт
Cветовой 7400 Лм
Степень 20 IP
Габаритные 1958х94х115 мм
В наличии 1
15 430 ₽
NEW=;PRODUCT_DAY_DATE_START=;PRODUCT_DAY_DATE_END=;PRODUCT_DAY_DATE=;HIT=;RECOMMEND=;CATEGORY=;ORDER_USE=;BACKGROUND_IMAGE=;BACKGROUND_YOUTUBE=;NEWPRODUCT=;DISCOUNT=;TIME_BUY=;TIME_BUY_FROM=;TIME_BUY_TO=;DELIVERY=;GIFT=;GUARANTEE=3 года;ACCESSORIES=;MINIMUM_PRICE=12800;MOSHNOSTY_VT=60;NAPRAGENIE_V=175-260;CHASTOTA_GH=50;KOEFFICIENT_MOSHNOSTI=0,98;SVETOVOY_POTOK_LM=5200;PYLSACHIA_SVETOVOGO_POTOKA=;CVETOVAY_TEMPERATYRA_K=4000;INDEKS_CVETOPEREDACHI_CRI=CRI 80+;TEMPERATURNY_DIAPAZON_T=0°...+45°С;UGOL_RASSEIVANIA_GR=120;STEPENY_ZASHITY_IP=20;KLIMATICHESKOE_ISPOLNENIYE_UHL=4;KLASS_ELEKTROBEZOPASNOSTI=I;TIP_RASSEIVATELYA=Матовый;MATERIAL_KORPUSA=;TIP_YSTANOVKI=Встраиваемый;PROIZVODITELE_SVETODIODOV=NICHIA;CHVET_KORPUSA=Белый;GABARITNYE_RAZMERY=1470х94х115;VZRYVOZASHITA=;KSS=Д;DISCOUNTS=;tip_pomesheniy=Торговые помещения и магазины;vote_count=;vote_sum=;rating=;FORMA_KORPUSA=;pylevlagozashchitnyy=НЕТ;TIP_KREPLENIY=;BAP=;kolichestvo_lamp=;tsokol=;datchiki=;ANALOG_DRL=;EMERGENCY=;EXPLOSION_PROOF=;DLINA=1470;WIDTH=94;HEIGHT=115;SHOW_IN_CATALOG=;MODEL_OFFICE=;MODEL_LINERAL=;MODEL_EMERGENCY=;PURPOSE=;EMERGENCY_2=;FEATURES=;MOUNTING_HEIGHT=;ACCESSORIES_2=;MODEL_INDUSTRIAL=;MODEL_UNPAVED=;MODEL_COMPONENTS=;MODEL_COMMERCIAL=;MODEL_DESIGN=;MODEL_STREET=;MODEL_EXPLOSION=;MODEL_architectural=;MODEL_ZHKH=;REQUEST_USE=;STORES_SHOW=;PICTURES=Array;ARTICLE=LE-СВО-23-060-1450-20Х / LE-СВО-23-060-1451-20Д / LE-СВО-23-060-1452-20Т;BRAND=106;ADDITIONAL=;VIDEO=Array;DOCUMENTS=Array;ASSOCIATED=;RECOMMENDED=;SERVICES=;MAIN_BANNER_SHOW=;MAIN_BANNER_PICTURE=;MAIN_BANNER_THEME=;PROPERTY_TYPE=;PROPERTY_QUANTITY_OF_STRIPS=;PROPERTY_POWER=;PROPERTY_PROCREATOR=Россия;PROPERTY_SCOPE=;PROPERTY_DISPLAY=;PROPERTY_WEIGTH=5;PROPERTY_ENERGY_CONSUMPTION=;PROPERTY_SETTINGS=;show =
LEDeffect СТРЕЛА СВО 60
Мощность, 60 Вт
Cветовой 5200 Лм
Степень 20 IP
Габаритные 1470х94х115 мм
В наличии 1
12 800 ₽
NEW=;PRODUCT_DAY_DATE_START=;PRODUCT_DAY_DATE_END=;PRODUCT_DAY_DATE=;HIT=;RECOMMEND=;CATEGORY=;ORDER_USE=;BACKGROUND_IMAGE=;BACKGROUND_YOUTUBE=;NEWPRODUCT=;DISCOUNT=;TIME_BUY=;TIME_BUY_FROM=;TIME_BUY_TO=;DELIVERY=;GIFT=;GUARANTEE=3 года;ACCESSORIES=;MINIMUM_PRICE=7870;MOSHNOSTY_VT=40;NAPRAGENIE_V=175-260;CHASTOTA_GH=50;KOEFFICIENT_MOSHNOSTI=0,98;SVETOVOY_POTOK_LM=3300;PYLSACHIA_SVETOVOGO_POTOKA=;CVETOVAY_TEMPERATYRA_K=4000;INDEKS_CVETOPEREDACHI_CRI=CRI 80+;TEMPERATURNY_DIAPAZON_T=0°...+45°С;UGOL_RASSEIVANIA_GR=120;STEPENY_ZASHITY_IP=20;KLIMATICHESKOE_ISPOLNENIYE_UHL=4;KLASS_ELEKTROBEZOPASNOSTI=I;TIP_RASSEIVATELYA=Матовый;MATERIAL_KORPUSA=;TIP_YSTANOVKI=Встраиваемый;PROIZVODITELE_SVETODIODOV=NICHIA;CHVET_KORPUSA=Белый;GABARITNYE_RAZMERY=990х94х115;VZRYVOZASHITA=;KSS=Д;DISCOUNTS=;tip_pomesheniy=Торговые помещения и магазины;vote_count=;vote_sum=;rating=;FORMA_KORPUSA=;pylevlagozashchitnyy=НЕТ;TIP_KREPLENIY=;BAP=;kolichestvo_lamp=;tsokol=;datchiki=;ANALOG_DRL=;EMERGENCY=;EXPLOSION_PROOF=;DLINA=990;WIDTH=94;HEIGHT=115;SHOW_IN_CATALOG=;MODEL_OFFICE=;MODEL_LINERAL=;MODEL_EMERGENCY=;PURPOSE=;EMERGENCY_2=;FEATURES=;MOUNTING_HEIGHT=;ACCESSORIES_2=;MODEL_INDUSTRIAL=;MODEL_UNPAVED=;MODEL_COMPONENTS=;MODEL_COMMERCIAL=;MODEL_DESIGN=;MODEL_STREET=;MODEL_EXPLOSION=;MODEL_architectural=;MODEL_ZHKH=;REQUEST_USE=;STORES_SHOW=;PICTURES=Array;ARTICLE=LE-СВО-23-040-1447-20Х / LE-СВО-23-040-1448-20Д / LE-СВО-23-040-1449-20Т;BRAND=106;ADDITIONAL=;VIDEO=Array;DOCUMENTS=Array;ASSOCIATED=;RECOMMENDED=;SERVICES=;MAIN_BANNER_SHOW=;MAIN_BANNER_PICTURE=;MAIN_BANNER_THEME=;PROPERTY_TYPE=;PROPERTY_QUANTITY_OF_STRIPS=;PROPERTY_POWER=;PROPERTY_PROCREATOR=Россия;PROPERTY_SCOPE=;PROPERTY_DISPLAY=;PROPERTY_WEIGTH=4;PROPERTY_ENERGY_CONSUMPTION=;PROPERTY_SETTINGS=;show =
LEDeffect СТРЕЛА СВО 40
Мощность, 40 Вт
Cветовой 3300 Лм
Степень 20 IP
Габаритные 990х94х115 мм
В наличии 1
7 870 ₽
NEW=;PRODUCT_DAY_DATE_START=;PRODUCT_DAY_DATE_END=;PRODUCT_DAY_DATE=;HIT=;RECOMMEND=;CATEGORY=;ORDER_USE=;BACKGROUND_IMAGE=;BACKGROUND_YOUTUBE=;NEWPRODUCT=;DISCOUNT=;TIME_BUY=;TIME_BUY_FROM=;TIME_BUY_TO=;DELIVERY=;GIFT=;GUARANTEE=3 года;ACCESSORIES=;MINIMUM_PRICE=5250;MOSHNOSTY_VT=20;NAPRAGENIE_V=175-260;CHASTOTA_GH=50;KOEFFICIENT_MOSHNOSTI=0,98;SVETOVOY_POTOK_LM=1600;PYLSACHIA_SVETOVOGO_POTOKA=;CVETOVAY_TEMPERATYRA_K=4000;INDEKS_CVETOPEREDACHI_CRI=CRI 80+;TEMPERATURNY_DIAPAZON_T=0°...+40°С;UGOL_RASSEIVANIA_GR=120;STEPENY_ZASHITY_IP=20;KLIMATICHESKOE_ISPOLNENIYE_UHL=4;KLASS_ELEKTROBEZOPASNOSTI=I;TIP_RASSEIVATELYA=Матовый;MATERIAL_KORPUSA=Алюминий;TIP_YSTANOVKI=Встраиваемый;PROIZVODITELE_SVETODIODOV=NICHIA;CHVET_KORPUSA=Белый;GABARITNYE_RAZMERY=512х94х115;VZRYVOZASHITA=;KSS=Д;DISCOUNTS=;tip_pomesheniy=Внутренние помещения;vote_count=;vote_sum=;rating=;FORMA_KORPUSA=;pylevlagozashchitnyy=;TIP_KREPLENIY=;BAP=;kolichestvo_lamp=;tsokol=;datchiki=;ANALOG_DRL=;EMERGENCY=;EXPLOSION_PROOF=;DLINA=512;WIDTH=94;HEIGHT=115;SHOW_IN_CATALOG=;MODEL_OFFICE=;MODEL_LINERAL=;MODEL_EMERGENCY=;PURPOSE=;EMERGENCY_2=;FEATURES=;MOUNTING_HEIGHT=;ACCESSORIES_2=;MODEL_INDUSTRIAL=;MODEL_UNPAVED=;MODEL_COMPONENTS=;MODEL_COMMERCIAL=;MODEL_DESIGN=;MODEL_STREET=;MODEL_EXPLOSION=;MODEL_architectural=;MODEL_ZHKH=;REQUEST_USE=;STORES_SHOW=;PICTURES=Array;ARTICLE=LE-СВО-23-020-1444-20Х / LE-СВО-23-020-1445-20Д / LE-СВО-23-020-1446-20Т;BRAND=106;ADDITIONAL=;VIDEO=Array;DOCUMENTS=Array;ASSOCIATED=;RECOMMENDED=;SERVICES=;MAIN_BANNER_SHOW=;MAIN_BANNER_PICTURE=;MAIN_BANNER_THEME=;PROPERTY_TYPE=;PROPERTY_QUANTITY_OF_STRIPS=;PROPERTY_POWER=;PROPERTY_PROCREATOR=Россия;PROPERTY_SCOPE=;PROPERTY_DISPLAY=;PROPERTY_WEIGTH=2;PROPERTY_ENERGY_CONSUMPTION=;PROPERTY_SETTINGS=;show =
LEDeffect СТРЕЛА СВО 20
Мощность, 20 Вт
Cветовой 1600 Лм
Степень 20 IP
Габаритные 512х94х115 мм
В наличии 1
5 250 ₽
NEW=;PRODUCT_DAY_DATE_START=;PRODUCT_DAY_DATE_END=;PRODUCT_DAY_DATE=;HIT=;RECOMMEND=;CATEGORY=;ORDER_USE=;BACKGROUND_IMAGE=;BACKGROUND_YOUTUBE=;NEWPRODUCT=;DISCOUNT=;TIME_BUY=;TIME_BUY_FROM=;TIME_BUY_TO=;DELIVERY=;GIFT=;GUARANTEE=3 года;ACCESSORIES=;MINIMUM_PRICE=30047;MOSHNOSTY_VT=56;NAPRAGENIE_V=230;CHASTOTA_GH=50;KOEFFICIENT_MOSHNOSTI=0,97;SVETOVOY_POTOK_LM=4500;PYLSACHIA_SVETOVOGO_POTOKA=;CVETOVAY_TEMPERATYRA_K=4000;INDEKS_CVETOPEREDACHI_CRI=CRI 80+;TEMPERATURNY_DIAPAZON_T=0°...+40°С;UGOL_RASSEIVANIA_GR=120°;STEPENY_ZASHITY_IP=20;KLIMATICHESKOE_ISPOLNENIYE_UHL=4;KLASS_ELEKTROBEZOPASNOSTI=II;TIP_RASSEIVATELYA=Матовый;MATERIAL_KORPUSA=Алюминий;TIP_YSTANOVKI=Встраиваемый;PROIZVODITELE_SVETODIODOV=;CHVET_KORPUSA=Черный;GABARITNYE_RAZMERY=2412x73x35, 2414x73x35, 2416x73x35;VZRYVOZASHITA=;KSS=Д;DISCOUNTS=;tip_pomesheniy=Офисные помещения;vote_count=;vote_sum=;rating=;FORMA_KORPUSA=;pylevlagozashchitnyy=;TIP_KREPLENIY=;BAP=;kolichestvo_lamp=;tsokol=;datchiki=;ANALOG_DRL=;EMERGENCY=;EXPLOSION_PROOF=;DLINA=2412, 2414, 2416;WIDTH=73;HEIGHT=35;SHOW_IN_CATALOG=;MODEL_OFFICE=;MODEL_LINERAL=;MODEL_EMERGENCY=;PURPOSE=;EMERGENCY_2=;FEATURES=;MOUNTING_HEIGHT=;ACCESSORIES_2=;MODEL_INDUSTRIAL=;MODEL_UNPAVED=;MODEL_COMPONENTS=;MODEL_COMMERCIAL=;MODEL_DESIGN=;MODEL_STREET=;MODEL_EXPLOSION=;MODEL_architectural=;MODEL_ZHKH=;REQUEST_USE=;STORES_SHOW=;PICTURES=Array;ARTICLE=1248001000, 1248002660, 1248006120, 1248007270;BRAND=104;ADDITIONAL=;VIDEO=Array;DOCUMENTS=Array;ASSOCIATED=;RECOMMENDED=;SERVICES=;MAIN_BANNER_SHOW=;MAIN_BANNER_PICTURE=;MAIN_BANNER_THEME=;PROPERTY_TYPE=;PROPERTY_QUANTITY_OF_STRIPS=;PROPERTY_POWER=;PROPERTY_PROCREATOR=Россия;PROPERTY_SCOPE=;PROPERTY_DISPLAY=;PROPERTY_WEIGTH=5.9;PROPERTY_ENERGY_CONSUMPTION=;PROPERTY_SETTINGS=;show =
СТ PROFILE 60R LED 2400 / DR LED 2400
Мощность, 56 Вт
Cветовой 4500 Лм
Степень 20 IP
Габаритные 2412x73x35, 2414x73x35, 2416x73x35 мм
В наличии 1
30 047 ₽
NEW=;PRODUCT_DAY_DATE_START=;PRODUCT_DAY_DATE_END=;PRODUCT_DAY_DATE=;HIT=;RECOMMEND=;CATEGORY=;ORDER_USE=;BACKGROUND_IMAGE=;BACKGROUND_YOUTUBE=;NEWPRODUCT=;DISCOUNT=;TIME_BUY=;TIME_BUY_FROM=;TIME_BUY_TO=;DELIVERY=;GIFT=;GUARANTEE=3 года;ACCESSORIES=;MINIMUM_PRICE=25650;MOSHNOSTY_VT=52;NAPRAGENIE_V=230;CHASTOTA_GH=50;KOEFFICIENT_MOSHNOSTI=0,97;SVETOVOY_POTOK_LM=4200;PYLSACHIA_SVETOVOGO_POTOKA=;CVETOVAY_TEMPERATYRA_K=;INDEKS_CVETOPEREDACHI_CRI=CRI 80+;TEMPERATURNY_DIAPAZON_T=0°...+40°С;UGOL_RASSEIVANIA_GR=120°;STEPENY_ZASHITY_IP=20;KLIMATICHESKOE_ISPOLNENIYE_UHL=4;KLASS_ELEKTROBEZOPASNOSTI=II;TIP_RASSEIVATELYA=Матовый;MATERIAL_KORPUSA=Алюминий;TIP_YSTANOVKI=Встраиваемый;PROIZVODITELE_SVETODIODOV=;CHVET_KORPUSA=Серый;GABARITNYE_RAZMERY=2114x73x35;VZRYVOZASHITA=;KSS=Д;DISCOUNTS=;tip_pomesheniy=Офисные помещения;vote_count=;vote_sum=;rating=;FORMA_KORPUSA=;pylevlagozashchitnyy=;TIP_KREPLENIY=;BAP=;kolichestvo_lamp=;tsokol=;datchiki=;ANALOG_DRL=;EMERGENCY=;EXPLOSION_PROOF=;DLINA=2114;WIDTH=73;HEIGHT=35;SHOW_IN_CATALOG=;MODEL_OFFICE=;MODEL_LINERAL=;MODEL_EMERGENCY=;PURPOSE=;EMERGENCY_2=;FEATURES=;MOUNTING_HEIGHT=;ACCESSORIES_2=;MODEL_INDUSTRIAL=;MODEL_UNPAVED=;MODEL_COMPONENTS=;MODEL_COMMERCIAL=;MODEL_DESIGN=;MODEL_STREET=;MODEL_EXPLOSION=;MODEL_architectural=;MODEL_ZHKH=;REQUEST_USE=;STORES_SHOW=;PICTURES=Array;ARTICLE=1248000980, 1248002650, 1248005920, 1248007280;BRAND=104;ADDITIONAL=;VIDEO=Array;DOCUMENTS=Array;ASSOCIATED=;RECOMMENDED=;SERVICES=;MAIN_BANNER_SHOW=;MAIN_BANNER_PICTURE=;MAIN_BANNER_THEME=;PROPERTY_TYPE=;PROPERTY_QUANTITY_OF_STRIPS=;PROPERTY_POWER=;PROPERTY_PROCREATOR=Россия;PROPERTY_SCOPE=;PROPERTY_DISPLAY=;PROPERTY_WEIGTH=5.1;PROPERTY_ENERGY_CONSUMPTION=;PROPERTY_SETTINGS=;show =
СТ PROFILE 60R LED 2100 / DR LED 2100
Мощность, 52 Вт
Cветовой 4200 Лм
Степень 20 IP
Габаритные 2114x73x35 мм
В наличии 1
25 650 ₽
NEW=;PRODUCT_DAY_DATE_START=;PRODUCT_DAY_DATE_END=;PRODUCT_DAY_DATE=;HIT=;RECOMMEND=;CATEGORY=;ORDER_USE=;BACKGROUND_IMAGE=;BACKGROUND_YOUTUBE=;NEWPRODUCT=;DISCOUNT=;TIME_BUY=;TIME_BUY_FROM=;TIME_BUY_TO=;DELIVERY=;GIFT=;GUARANTEE=3 года;ACCESSORIES=;MINIMUM_PRICE=22131;MOSHNOSTY_VT=40;NAPRAGENIE_V=230;CHASTOTA_GH=50;KOEFFICIENT_MOSHNOSTI=0,97;SVETOVOY_POTOK_LM=3800;PYLSACHIA_SVETOVOGO_POTOKA=;CVETOVAY_TEMPERATYRA_K=4000;INDEKS_CVETOPEREDACHI_CRI=CRI 80+;TEMPERATURNY_DIAPAZON_T=0°...+40°С;UGOL_RASSEIVANIA_GR=120°;STEPENY_ZASHITY_IP=20;KLIMATICHESKOE_ISPOLNENIYE_UHL=4;KLASS_ELEKTROBEZOPASNOSTI=II;TIP_RASSEIVATELYA=Матовый;MATERIAL_KORPUSA=;TIP_YSTANOVKI=Встраиваемый;PROIZVODITELE_SVETODIODOV=;CHVET_KORPUSA=Серый;GABARITNYE_RAZMERY=1812x73x35;VZRYVOZASHITA=;KSS=Д;DISCOUNTS=;tip_pomesheniy=Торговые помещения и магазины;vote_count=;vote_sum=;rating=;FORMA_KORPUSA=;pylevlagozashchitnyy=НЕТ;TIP_KREPLENIY=;BAP=;kolichestvo_lamp=;tsokol=;datchiki=;ANALOG_DRL=;EMERGENCY=;EXPLOSION_PROOF=;DLINA=1812;WIDTH=73;HEIGHT=35;SHOW_IN_CATALOG=;MODEL_OFFICE=;MODEL_LINERAL=;MODEL_EMERGENCY=;PURPOSE=;EMERGENCY_2=;FEATURES=;MOUNTING_HEIGHT=;ACCESSORIES_2=;MODEL_INDUSTRIAL=;MODEL_UNPAVED=;MODEL_COMPONENTS=;MODEL_COMMERCIAL=;MODEL_DESIGN=;MODEL_STREET=;MODEL_EXPLOSION=;MODEL_architectural=;MODEL_ZHKH=;REQUEST_USE=;STORES_SHOW=;PICTURES=Array;ARTICLE=1248000970, 1248002600, 1248006110;BRAND=104;ADDITIONAL=;VIDEO=Array;DOCUMENTS=Array;ASSOCIATED=;RECOMMENDED=;SERVICES=;MAIN_BANNER_SHOW=;MAIN_BANNER_PICTURE=;MAIN_BANNER_THEME=;PROPERTY_TYPE=;PROPERTY_QUANTITY_OF_STRIPS=;PROPERTY_POWER=;PROPERTY_PROCREATOR=Россия;PROPERTY_SCOPE=;PROPERTY_DISPLAY=;PROPERTY_WEIGTH=2.5;PROPERTY_ENERGY_CONSUMPTION=;PROPERTY_SETTINGS=;show =
СТ PROFILE 60R LED 1800
Мощность, 40 Вт
Cветовой 3800 Лм
Степень 20 IP
Габаритные 1812x73x35 мм
В наличии 1
22 131 ₽
NEW=;PRODUCT_DAY_DATE_START=;PRODUCT_DAY_DATE_END=;PRODUCT_DAY_DATE=;HIT=;RECOMMEND=;CATEGORY=;ORDER_USE=;BACKGROUND_IMAGE=;BACKGROUND_YOUTUBE=;NEWPRODUCT=;DISCOUNT=;TIME_BUY=;TIME_BUY_FROM=;TIME_BUY_TO=;DELIVERY=;GIFT=;GUARANTEE=3 года;ACCESSORIES=;MINIMUM_PRICE=18906;MOSHNOSTY_VT=34;NAPRAGENIE_V=230;CHASTOTA_GH=50;KOEFFICIENT_MOSHNOSTI=0,97;SVETOVOY_POTOK_LM=3000;PYLSACHIA_SVETOVOGO_POTOKA=;CVETOVAY_TEMPERATYRA_K=4000;INDEKS_CVETOPEREDACHI_CRI=CRI 80+;TEMPERATURNY_DIAPAZON_T=0°...+40°С;UGOL_RASSEIVANIA_GR=120°;STEPENY_ZASHITY_IP=20;KLIMATICHESKOE_ISPOLNENIYE_UHL=4;KLASS_ELEKTROBEZOPASNOSTI=II;TIP_RASSEIVATELYA=Матовый;MATERIAL_KORPUSA=;TIP_YSTANOVKI=Встраиваемый;PROIZVODITELE_SVETODIODOV=;CHVET_KORPUSA=Черный;GABARITNYE_RAZMERY=1511x73x35;VZRYVOZASHITA=;KSS=Д;DISCOUNTS=;tip_pomesheniy=Офисные помещения;vote_count=;vote_sum=;rating=;FORMA_KORPUSA=;pylevlagozashchitnyy=НЕТ;TIP_KREPLENIY=;BAP=;kolichestvo_lamp=;tsokol=;datchiki=;ANALOG_DRL=;EMERGENCY=;EXPLOSION_PROOF=;DLINA=1511;WIDTH=73;HEIGHT=35;SHOW_IN_CATALOG=;MODEL_OFFICE=;MODEL_LINERAL=;MODEL_EMERGENCY=;PURPOSE=;EMERGENCY_2=;FEATURES=;MOUNTING_HEIGHT=;ACCESSORIES_2=;MODEL_INDUSTRIAL=;MODEL_UNPAVED=;MODEL_COMPONENTS=;MODEL_COMMERCIAL=;MODEL_DESIGN=;MODEL_STREET=;MODEL_EXPLOSION=;MODEL_architectural=;MODEL_ZHKH=;REQUEST_USE=;STORES_SHOW=;PICTURES=Array;ARTICLE=1248000960, 1248002610, 1248006100;BRAND=104;ADDITIONAL=;VIDEO=Array;DOCUMENTS=Array;ASSOCIATED=;RECOMMENDED=;SERVICES=;MAIN_BANNER_SHOW=;MAIN_BANNER_PICTURE=;MAIN_BANNER_THEME=;PROPERTY_TYPE=;PROPERTY_QUANTITY_OF_STRIPS=;PROPERTY_POWER=;PROPERTY_PROCREATOR=Россия;PROPERTY_SCOPE=;PROPERTY_DISPLAY=;PROPERTY_WEIGTH=2.1;PROPERTY_ENERGY_CONSUMPTION=;PROPERTY_SETTINGS=;show =
СТ PROFILE 60R LED 1500
Мощность, 34 Вт
Cветовой 3000 Лм
Степень 20 IP
Габаритные 1511x73x35 мм
В наличии 1
18 906 ₽
NEW=;PRODUCT_DAY_DATE_START=;PRODUCT_DAY_DATE_END=;PRODUCT_DAY_DATE=;HIT=;RECOMMEND=;CATEGORY=;ORDER_USE=;BACKGROUND_IMAGE=;BACKGROUND_YOUTUBE=;NEWPRODUCT=;DISCOUNT=;TIME_BUY=;TIME_BUY_FROM=;TIME_BUY_TO=;DELIVERY=;GIFT=;GUARANTEE=3 года;ACCESSORIES=;MINIMUM_PRICE=23518;MOSHNOSTY_VT=30;NAPRAGENIE_V=230;CHASTOTA_GH=50;KOEFFICIENT_MOSHNOSTI=0,97;SVETOVOY_POTOK_LM=2400;PYLSACHIA_SVETOVOGO_POTOKA=;CVETOVAY_TEMPERATYRA_K=;INDEKS_CVETOPEREDACHI_CRI=CRI 80+;TEMPERATURNY_DIAPAZON_T=+5°...+35°С;UGOL_RASSEIVANIA_GR=120°;STEPENY_ZASHITY_IP=20;KLIMATICHESKOE_ISPOLNENIYE_UHL=4;KLASS_ELEKTROBEZOPASNOSTI=II;TIP_RASSEIVATELYA=Матовый;MATERIAL_KORPUSA=;TIP_YSTANOVKI=Встраиваемый;PROIZVODITELE_SVETODIODOV=;CHVET_KORPUSA=Белый;GABARITNYE_RAZMERY=1206x73x35, 1210x73x35;VZRYVOZASHITA=;KSS=Д;DISCOUNTS=;tip_pomesheniy=Внутренние помещения;vote_count=;vote_sum=;rating=;FORMA_KORPUSA=;pylevlagozashchitnyy=НЕТ;TIP_KREPLENIY=;BAP=;kolichestvo_lamp=;tsokol=;datchiki=;ANALOG_DRL=;EMERGENCY=;EXPLOSION_PROOF=;DLINA=1206, 1210;WIDTH=73;HEIGHT=35;SHOW_IN_CATALOG=;MODEL_OFFICE=;MODEL_LINERAL=;MODEL_EMERGENCY=;PURPOSE=;EMERGENCY_2=;FEATURES=;MOUNTING_HEIGHT=;ACCESSORIES_2=;MODEL_INDUSTRIAL=;MODEL_UNPAVED=;MODEL_COMPONENTS=;MODEL_COMMERCIAL=;MODEL_DESIGN=;MODEL_STREET=;MODEL_EXPLOSION=;MODEL_architectural=;MODEL_ZHKH=;REQUEST_USE=;STORES_SHOW=;PICTURES=Array;ARTICLE=1248001630/1248000690;BRAND=104;ADDITIONAL=;VIDEO=Array;DOCUMENTS=Array;ASSOCIATED=;RECOMMENDED=;SERVICES=;MAIN_BANNER_SHOW=;MAIN_BANNER_PICTURE=;MAIN_BANNER_THEME=;PROPERTY_TYPE=;PROPERTY_QUANTITY_OF_STRIPS=;PROPERTY_POWER=;PROPERTY_PROCREATOR=Россия;PROPERTY_SCOPE=;PROPERTY_DISPLAY=;PROPERTY_WEIGTH=1.7, 2.9;PROPERTY_ENERGY_CONSUMPTION=;PROPERTY_SETTINGS=;show =
СТ PROFILE 60R DR LED 1200 / 60R LED 1200
Мощность, 30 Вт
Cветовой 2400 Лм
Степень 20 IP
Габаритные 1206x73x35, 1210x73x35 мм
В наличии 1
23 518 ₽
Показать еще
1
2
Нужна консультация?
Подробно расскажем о наших услугах, видах работ и типовых проектах, рассчитаем стоимость и подготовим индивидуальное предложение!
О компании
Услуги
Помощь
Покупки
Помощь покупателю
Вопрос - ответ
Бренды
Коллекции
Готовые образы
Возможности
+7 (499) 113 27 70
info+161896@keosvet.ru
г. Москва, ул. Иркутская 11 к1 оф.135
© 2023 Universe, Все права защищены
Добавить элементИзменить разделДобавить разделУдалить разделРедактировать пункты менюСоздать товар с торговыми предложениями
